*
A)	CONCEPT OF OUTPUT DELIVERY SYSTEM

	--->	ODS STANDS FOR OUTPUT DELIVERY SYSTEM. A PROCEDURE IN PROGRAM DOESN'T PRODCUE RESULT, INSTEAD A PROCEDURES ONLY PRODUCE DATA.
			THEN THEY SEND THE DATA TO OUTPUT DELIVERY SYSTEM WHICH DETERMINES WHERE THE OUTPUT SHOULD GO AND WHAT IT SHOULD LOOK LIKE 
			WHEN IT GET'S THERE. THAT MEANS THE QUESTION TO ASK YOURSEFL IS NOT WEATHER WEATHER YOU WANT TO USE ODS. YOU ALWAYS USE ODS. 
			WEATHER  YOU ACCEPT DEFAULT OUPT OR CHOOSE SOEMTHING ELSE.


	--->	DESTINATIONS --- IF YOU DO NOT SPECIFY ODS YOUR OUTOUT WILL BE SENT TO DEFAULT OUTPUT WHICH IS HTML.

	--->			HTML 				HYPERTEXT MARKUP LANGUAGE
					LISTING				TEXT OUTPUT
					PDF					PORTABLE DOCUMENT FORMAT
					PS					POSTSCRIPT
					PRINTER				HIGH-RESOLUTION PRINTER OUTPUT
					RTF					RICH TEXT FORMAT
					MARKUP				MARKUP LANGUAGE INCLUDING XML
					DOCUMENT 			OUPUT DOCUMENT
					OUTPUT				SAS DATA OUTPUT

	--->	STYLE AND TABLE TEMPLATES --- TEMPLATES TELLS ODS HOW TO FORMAT AND PRESENT YOUR DATA.

	--->	TWO MOST COMMON TYPE OF TEMPLATES ARE "TABLE" TEMPLATES AND "STYLE" TEMPALETS (ALSO CALLED TABLE DEFINITIONS AND STYLE DEFINITIONS)

	--->	A TABLE TEMPLATE SPECIFY THE BASIC STRUCTURE OF YOUR OUTPUT ( WHICH VARIABLE IN FIRST COLUMN)

	--->	WHILE A STYLE TEMPLATE SPECIFIES HOW THE OUTPUT WILL LOOK. ( WILL THE HEADER BE BLUE OR RED)

	--->	YOU CAN CREATE YOUR OWN STYLE AND TABLE TEMPLATE BY USING THE "TEMPLATE" PROCEDURE. 

	--->	FORTUNATLY, THERE ARE OTHER EAISER WAY TO CONTROL AND MODIFY OUTPUT. THE QUICKEST AND EASIEST WAY TO CHANGE THE LOOK OF YOUR OUTPUT
			IS TO USE ONE OF THE MANY BULIT-IN STYLE TEMPLATE. 

	--->	TO VIEW A LIST OF OF STYLE TEMPLATES AVAILABLE ON YOUR SYSTEM, SUBMIT THE FOLLOWNG "PROC TEMPLATE" STATEMENT.;
	

PROC TEMPLATE;
LIST STYLES;
RUN; *

	--->	NOTE "RTF" AND "PRINTER" ARE NAMES OF BOTH DESTINATIONS AND STYLE. SOME STYLES ARE BETTER WITH CERTAIN DESTINATION THEN OTHERS.

	--->	"HTMLBLUE" IS THE DEFAULT STYLE FOR HTML OUTPUT, "RTF" IS DEFAULT STYL FOR RTF OUTPUT.

	--->	FEW PROCEDURES, MOST NOTABLY "PRINT", "REPORT", AND "TABULATE" DON'T HAVE READY MADE TABLE TEMPLATES. INSTEAD THE SYNTAX FOR THESE
			PROCDURES ACTS LIKE CUSTOME TABLE TEMPLATE. WHILE ALL TABLE THAT PRODUCE PRINTABLE OUTPUT ALLOW YOU TO USE STYLE TEMPLATE TO CONTROLL
			OVERALL LOOK OF THAT OUTPUT., THESE 3 PROCEDURES ALSO ALLOW YOU TO DO SOMETHING SPECIAL. 

	--->	WITH "PRINT", "REPORT" AND "TABULATE" YOU CAN USE "STYLE=" OPTION DIRECTLY IN THE PROC STEP TO CONTROLL INDIVIDUAL FEATURES OF YOUR
			OUTPUT WITHOUT HAVING TO CREATE A WHOLE NEW STYLE TEMPLATE.


B)	TRACING AND SELECTING PROCEDURE OUPUT
	--->	FOR MOST PROCEDURES WHEN YOU USE "BY" STATEMENT SAS PRODUCES ONE OUTPUT OBJECT FOR EACH BY GROUP. 

	--->	EACH OBJECT OUTPUT HAS A NAME. YOU CAN FIND THE NAME OF OUTPUT OBJECTS BY USING THE "ODS TRACE" STATEMENT. THEN YOU CAN USE AN 
			"ODS SELECT" (OR "ODS EXCLUDE") STATEMENT TO CHOOSE JUST THE OUTPUT OBJECT YOU NEEDED.  

	--->	ODS TRACE STATEMENT --- THE "ODS TRACE" STATEMENT TELLS SAS TO PRINT INFORMATION ABOUT OUTPUT OBJECTS IN YOUR SAS LOG. THERE ARE
			TWO ODS TRACE STATEMENTS. ONE TO TURN THE TRACE AND ANOTHER TO TURN OFF THE TRACE.

					ODS TRACE ON:
					the PROC steps you want to trace to go here
					RUN:
					ODS TRACE OFF:

	--->	;


DATA TOMATTO;
INFILE "D:\Practice\SAS\Little SAS Book\Data\tomatto.csv" DSD DLM="," FIRSTOBS=2;
INPUT NAME : $20. COLOUR : $7. HARVEST_IN_DAYS : 2. WEIGHT : 3. ;
RUN;
ODS TRACE ON;
PROC MEANS DATA=TOMATTO;
BY COLOUR;
RUN;
ODS TRACE OFF;  *

	--->	ODS SELECT STATEMENT -- ONCE YOU KNOW THE NAMES OF THE OUTPUT OBJECTS, YOU CAN USE AN "ODS SELECT" (OR EXCLUDE) STATEMENT TO CHOOSE
			JUST TO OUTPUT OBJECTS YOU WANT. THE GENERAL FORM OF AN "ODS SELECT" IS

					The PROC Step with the output objects you want to select 
					ODS SELECT output-object-list:
					RUN:

	--->	BY DEFAULT "ODS SELECT" STATEMENT LAST FOR ONLY ONE STATEMENT. "ODS EXCLUDE" STATEMENT WORKS THE SAME WAY EXCEPT YOU LIST THE OBECT
			YOU WANT TO ELIMINATE.

	--->	;

PROC MEANS DATA= TOMATTO;
BY COLOUR;
ODS SELECT MEANS.BYGROUP1.SUMMARY;
RUN;		*


C)	CREATING SAS DATA SETS FROM PROCEDURE OUTPUT

	--->	SOMETIMES YOU MAY WANT TO PUT THE RESULTS FROM A PROCEDURE INTO A SAS DATASET. ONCE THE RESULTS ARE IN A DATA SET, YOU CAN MERGE THEM
			WITH ANOTHER DATA SET, COMPUTE NEW VARIABLES BASES ON THE RESULTS, OR USE THE RESULTS AS INPUT FOR OTHER PRECEDURES. SOME PROCEDURES
			HAVE "OUTPUT" STATEMENT, OR OUT=OPTIONS,A ALLOWING YOU TO SAVE THE RESULTS AS A SAS DATA SET. BUT WITH "ODS" YOU CAN SAVE ALMOST ANY
			PART OF PROCEDURE OUTPUT AS A SAS DATA SET BY SENDING IT TO THE "OUPUT" DESTINATION. FIRST YOU USE AN "ODS TRACE" STATEMENT TO 
			DETERMINE THE NAME OF THE OUTPUT OBJECT YOU WANT. THEN YOU USE AN "ODS OUPUT" STATEMENT TO SEND THAT OBJECT TO THE "OUPUT" DESTINATION.

	--->	ODS OUTPUT STATEMENT -- 

					ODS OUTPUT output-object = new-data-set:

	--->	THE "ODS OUTPUT" STATEMENT DOESN'T BELONG TO EITHER A "DATA" OR "PROC" STEP. THE "ODS OUTPUT" STATEMENT OPENS A SAS DATASET AND WAITS
			FOR THE CORRET PROCEDURE OUTPUT. THE DATASET REMAINS OPNEN UNTIL THE NEXT ENCOUNTER WITH THE END OF "PROC" STEP. BECAUSE THE 
			"ODS OUPUT" STATEMENT EXECUTES IMMEDIATELY, IT WILL APPLY TO WHATEVER "PROC" IS CURRENTLY BEING PROCESSED, OR WILL APPLY TO NEXT "PROC"
			IF THERE IS NOT A CURRENT "PROC". TO ENSURE THAT YOU GET CORRECT OUTPUT, WE RECOMMAND YOU TO PUT THE "ODS OUPUT" STATEMET AFTER YOUR
			"PROC" STATEMENT, AND BEFORE THE NEXT "PROC" , "DATA" OR "RUN" STATEMENT.
	
	--->	;


DATA TOMATTO1;
INFILE "D:\Practice\SAS\Little SAS Book\Data\tomatto.csv" DSD DLM="," FIRSTOBS=2;
INPUT NAME : $15. COLOUR : $6. HARVEST_IN_DAYS : 4. WEIGHT : 2.;
RUN;
ODS TRACE ON;
PROC TABULATE DATA = TOMATTO1;
CLASS COLOUR;
VAR HARVEST_IN_DAYS WEIGHT;
TABLE COLOUR ALL,(HARVEST_IN_DAYS WEIGHT) * MEAN;
RUN;
ODS TRACE OFF;



PROC TABULATE DATA = TOMATTO1;
CLASS COLOUR;
VAR HARVEST_IN_DAYS WEIGHT;
TABLE COLOUR ALL,(HARVEST_IN_DAYS WEIGHT)* MEAN;
TITLE 'STANDARD TABULATE OUTPUT';
ODS OUTPUT TABLE = TABOUT;
RUN;
PROC PRINT DATA=TABOUT;
TITLE 'SAS OUTPUT DATA SET FROM TABLULATE ';
RUN; *


D)	CREATING TEXT OUPUT
	--->	THE LISTING DESTINATION CREATES SIMPLE TEXT OUTPUT. TEXT OUTPUT CONSISTS OF BASIC CHARACTERS WITHOUT THE SPECIAL FORMATTING ADDED
			BY APPLICATIONS SUCH AS WORD PROCESSORS OR SPREADSHEETS. TEXT OUTPUT HAS SOME ADVANTAGES. IT IS HIGHLY PORTABLE, COMPACT WHEN PRINTED,
			CAN EASILY EDITED. "LISTING" IS THE DEFAULT DESTINATION WHN YOU RUN SAS IN BATCH OR IN THE Z/OS OPERATING ENVIRONMENT. IF YOU WANT
			TO PRODUCE "LISTING" OUTPUT IN THE SAS WINDOWING ENVIRONMENT IN MRICROSOFT WINDOW OR UNIX, THEN YOU MUST OPEN THE "LISTING" DESTINATION.
			THERE ARE TWO WAYS TO DO THIS, EITHER BY SUBMITTING AN "ODS LISTING" STATEMENT OR VIA THE TOOL MENU.

	--->	TOOL MENU --- IN THE SAS WINDOWING ENVIONMENT, YOU CAN OPEN THE "LISTING" DESTINATION BY SELECTING TOOLS => OPTIONS => PREFERENCES 
			FROM THE MENU BAR. THEN CLICK THE RESULT TAB AND CHECK THE BOX NEXT TO CREATE LISTING. SAS WILL CONTINUE TO SEND OUTPUT TO THE 
			"LISTING" DESTINATION UNTILL YOU CLOSE IT. 

	--->	"ODS" STATEMENT --- YOU CAN ALSO OPEN THE "LISTING" BY SUBMITTING AN "ODS LISTING" STATEMENT. THE GENERAL FORM OF THIS STATEMENT IS

						ODS LISTING:

	--->	IF YOU SUBMIT THIS STATMENT, THEN YOUR OUTPUT WILL BE DISPLAYED IN THE OUTPUT WINDOW. IF YOU ADD A "FILE=" OPTIONS. THEN YOUR OUTPUT
			WILL BE SAVED IN A FILE INSTEAD, AND WILL NOT APPER IN THE OUPUT WINDOW. THE FOLLOWING STATEMENT TELLS SAS TO SEND THE OUTPUT TO THE
			"LISTING" DESTINATION AND SAVE THE RESULTS IN A FILE NAMED "ANNUALREPORT.LST"

						ODS LISTING FILE = "ANNUALREPORT.LST"
	--->	UNLIKE MOST "ODS" DESTINATION, YOU DO NOT NEED TO CLOSE THE "LISTING" DESTINATION IN THE ORDER TO SEE YOUR OUTPUT. THE ONLY REASON 
			TO CLOSE THE "LISTING" DESTINATION IS IF YOU WANT TO STOP PRODUCING TEXT OUPUT. HERE IS THE "ODS" STATEMENT WHICH CLOSS THE "LISTING"
			DESTINATION.
						ODS LISTING CLOSE:

	--->	REMOVING PRODECURE TITLES --- SOME PROCEDURES (SUCH AS PROC MEANS AND PROC FREQ) INCLUDE THE NAME OF THE PROCEDURE IN YOUR OUPUT.
			YOU CAN REMOVE PROCEDURE NAMES BY USING THE "ODS NOPROCTITLE" STATEMENT. THIS STATEMENT WORKS FOR ALL DESTINATION, NOT JUST "LISTING"
						ODS NOPROCTITLE;


ODS LISTING;
ODS NOPROCTITLE;
DATA FISH;
INFILE "D:\Practice\SAS\Little SAS Book\Data\Whale & Shark.csv" DSD DLM="," FIRSTOBS=2;
INPUT NAME : $10.	FAMILY : $10.	LENGHTH;
RUN;
PROC MEANS DATA = FISH MEAN MAX MIN;
CLASS FAMILY;
TITLE "SHARK & WHALE";
RUN;
PROC PRINT DATA = FISH;
RUN;



