*
E)	CREATING HTML OUPUT
	--->	STARTING FROM SAS 9.3 "HTML" OUTPUT IS THE DEFAULT IN THE SAS WINDOWING ENVIRONMENT IN MICROSOFT WINDOWS AND UNIX SO YOU DO NOT 
			NEED TO USE "ODS" STATEMENTS TO OPEN OR CLOSE THE DESTINATION. HOWEVER, YOU MAY STILL WANT TO USE "ODS" STATEMENTS TO SPECIFY OPTIONS.
			IF YOU ARE RUNNING IN BATCH OR IN OTHER OPERATING ENVIRONMENTS, THEN YOU NEED TO USE ODS STATEMTS TO PRODUCE "HTML" OUTPUT.

	--->	"ODS" STATEMENT TO OPEN THE "HTML" DESTINATION, USE THE "ODS HTML" STATEMENT. GENERAL SYNTAX OF THIS STATEMENT IS
					ODS HMTL BODY = "body-filename.html" options:

	--->	THE BODY FILE CONTAINS YOUR RESULTS. THE "FILE=" OPTION IS SYNONMOUS WITH "BODY=" OTHER OPTIONS AVAILABLE FOR DESTINATION INCLUDE.

	--->	CONTENTS	= "FILENAME"		CREATES A TABLE OF CONTENTS WITH LINKS TO THE BODY FILE
			PAGE		= "FILENAME"		CREATES A TABLE OF CONTENTS WITH LINKS BY PAGE NUMBER
			FRAME		= "FILENAME"		CREATES A FRAME THAT ALLOWS YOU TO VIEW THE BODY FILE AND THE CONTENTS OR THE PAGE FILE AT THE SAME
											TIME. IF YOU DO NOT WANT EITHER THE CONTENTS OR THE PAGE FILE, THEN YOU DON'T NEED TO CREATE A FRAME
											FILE.
	--->	STYLE		= "STYLE-NAME"		SPECIFIES A STYLE TEMPLATE. THE DEFAULT IS HTMLBLUE.

	--->	YOU ALWAYS WANT TO CREATE A BODY FILE, BUT THE OTHER FILES ARE OPTIONAL. THE FOLLOWING STATEMENT TELLS SAS TO SEND OUTPUT TO THE "HTML"
			DESTINATION, SAVE THE RESULT IN THE FILE NAMED ANNUALREPORT.HTML AND USE BARRETTSBLUE STYLE.
					ODS HTML FILE = 'AnnualReport.html' STYLE = BARRETTSBLUE:

	--->	TO CLOSE THE HTML DESTINATION, PUT THIS STATEMENT AFTER THE STEP WHOSE OUTPUT YOU WISH TO CAPTURE, AND FOLLOWING A "RUN" STATEMENT.
					ODS HTML CLOSE:

	--->	;

ODS HTML STYLE = D3D 
BODY = "D:\Practice\SAS\Little SAS Book\Whale & Shark.html"
FRAME= "D:\Practice\SAS\Little SAS Book\Whale & Shark FRAME.html"
CONTENTS= "D:\Practice\SAS\Little SAS Book\Whale & Shark TOC.html";
ODS NOPROCTITLE;
DATA FISH;
INFILE "D:\Practice\SAS\Little SAS Book\Data\Whale & Shark.csv" DSD DLM="," FIRSTOBS=2;
INPUT NAME : $10.	FAMILY : $10.	LENGTH;
RUN;
PROC MEANS DATA = FISH MEAN MAX MIN;
CLASS FAMILY;
TITLE "WHALE & SHARK";
RUN;
PROC PRINT DATA=FISH;
RUN;
ODS HTML CLOSE; 		*

F)	CREATING RTF OUTPUT
	--->	WHEN YOU CREATE "RTF" OUTPUT, YOU CAN COPY IT INTO A WORD DOCUMENT AND EDIT OR RESIZE IT LIKE OTHER WORD TABLES. SENDING OUTPUT TO RTF
			IS SIMILAR TO SENDING IT TO THE "HTML" DESTINATION EXCEPT YOU USE "ODS RTF" STATEMENT.

	--->	ODS STATEMENT --- THE GENERAL SYNTAX FOR ODS FILE IN RTF IS
					ODS RTF FILE = 'filename.rtf' options:

	--->	HERE ARE SOME OF THE MOST COMMONLY USED OPTIONS FOR THE DISTINATION.
					
					BODYTILE					PUTS TITLE AND FOOTNOTES IN THE MAIN PART OF 
												"RTF" DOCUMENT INSTEAD OF IN WORD HEADERS OR FOOTERS.

					COLUMN	=	n				REQUEST COLUMANER OUPUT WHERE n IS NUMBER OF OUPUT
				
					SASDATE						BY DEFAULT TH DATE AND TIME THAT APPERS AT THE TOP OF RTF OUTPUT
												INDICATES WHEN THE FILE WAS LAST OPENED OR PRINTED IN WORD. THIS 
												OPTION TELLS SAS TO USE THE DATE AND TIME WHEN THE CURRENT SAS SESSION
												STARTED RUNNING.

					STARTPAGE = value			CONTROLS PAGE BREAKS. THE DEFAULT VALUE, "YES", INSERTED A PAGE BREAK
												BETWEEN PROCEDURES. A VALUE OF "NO" TURNS OFF PAGE BREAKS. A VALUE OF 
												"NOW" INSERET A PAGE BREAK AT THAT POINT.

					STYLE	= style-name		SPECIFIC A STYLE TEMPLATE. THE DEFAULT IN "RTF"

	--->	THE FOLLOWING STATEMENT TELLS SAS TO SEND OUTPUT TO THE "RTF" DESTINATION, SAVE THE RESULT IN A FILE NAMED ANNUALREPORT.RTF AND USE
			SANSPRINTER STYLE:
					ODS RTF FILE = 'AnnualReport.rtf' STYLE = SANSPRINTER:

	--->	;


ODS RTF FILE = "D:\Practice\SAS\Little SAS Book\Whale & Shark.rtf"
BODYTITLE STARTPAGE = NO;
ODS NOPROCTITLE;
DATA FISH3;
INFILE "D:\Practice\SAS\Little SAS Book\Data\Whale & Shark.csv" DSD DLM="," FIRSTOBS=2;
INPUT NAME : $10.	FAMILY : $10.	LENGTH;
RUN;
PROC MEANS DATA = FISH3 MEAN MAX MIN;
CLASS FAMILY;
TITLE "WHALE & SHARK";
RUN;
PROC PRINT DATA=FISH3;
RUN;
ODS RTF CLOSE; 		*


G)	CREATING PDF OUTPUT

	--->	ODS STATEMENT -- THE GENERAL SYNTAX FOR THE ODS STATEMENT TO PRINT PDF DESTINATION IS
					ODS PDF FILE = "FILENAME.PDF" OPTIONS:

	--->	LIKE THE "DESTINATION", THE PDF DESTINATION PRODUCES ONLY ONE KIND OF FILE, A FILE CONTAING OUTPUT. THE OPTIONS AVAILABLE FOR THIS
			DESTINATION ENCLUDE.

					COLUMNS = n 			REQUEST COLUMANER OUTPUT WHERE n IS THE NUMBER OF COLUMNS.

					STARTPAGE = vlaue		CONTROLS PAGE BREAKS. THE DEFAULT VALUE, "YES", INSERTED A PAGE BREAK
											BETWEEN PROCEDURES. A VALUE OF "NO" TURNS OFF PAGE BREAKS. A VALUE OF 
											"NOW" INSERET A PAGE BREAK AT THAT POINT.

					STYLE = style-name		SPECIFIES A STYLE TEMPLATE. THE DEFAULT IS PRINTER.

	--->	THE FOLLOWING STATEMENT TELLS SAS TO CREATE "PDF" OUTPUT, SAVE THE RESULTS IN A FILE NAMED ANNUALREPORT.PDF, AND USE SANSPRINTER STYLE.
					ODS PDF FILE = 'AnnualReport.pdf' STYLE = SANSPRINTER;



ODS PDF FILE = "D:\Practice\SAS\Little SAS Book\Whale & Shark.pdf"
STARTPAGE = NO;
ODS NOPROCTITLE;
DATA FISH5;
INFILE "D:\Practice\SAS\Little SAS Book\Data\Whale & Shark.csv" DSD DLM="," FIRSTOBS=2;
INPUT NAME : $10.	FAMILY : $10.	LENGTH;
RUN;
PROC MEANS DATA = FISH5 MEAN MAX MIN;
CLASS FAMILY;
TITLE "WHALE & SHARK";
RUN;
PROC PRINT DATA=FISH5;
RUN;
ODS PDF CLOSE; 		*


H)	CUSTOMIZING TITLES AND FOOTNOTES
	--->	THE GENERAL FORM FOR A "TITLE" OR "FOOTNOTE" STATEMENT IS
					TITLE options 'text-string-1' options 'text-string-2' ... options 'text-string-n': 
					FOOTNOTE options 'text-string-1' options 'text-string-2' ...options 'text-string-n':

	--->	TEXT CAN BE BROKEN INTO PIECES WITH DIFFERENT OPTIONS FOR EACH PIECE. SAS WILL CONCATENATE TEXT STRINGS JUST THE WAY YOU TYPE THEM,
			SO TO BE SURE TO INCLIDE ANY NECESSARY BLNAKS. EACH OPTION APPLIES TO THE TEXT STRING THAT FOLLOWS, AND STAYS IN EFFECT UNTIL ANOTHER
			VALUE IS SPECIFIED FOR THAT OPTION, OR UNTIL THE END OF THE STATEMENT.

					COLOUR 	= SPECIFIES A COLOUR FOR THE TEXT
					BCOLOUR = SPECIFIES A COLOR FOR THE BACKGROUND OF THE TEXT
					HEIGHT	= SPECIFIES THE HEIGHT OF THE TEXT
					JUSTIFY	= REQUESTS JUSTIFICATION
					FRONT	= SPECIFIES A FONT FOR THE TEXT
					BOLD	= MAKES TEXT BOLD
					ITALIC	= MAKES TEXT ITALIC

	--->	COLOUR ---THE "COLOR=" OPTION SPECIFIES THE COLOR OF THE TEXT. THIS STATEMENT
					TITLE COLOR=BLACK 'Black  ' COLOR=GRAY 'Gray  ' COLOR=LTGRAY 'Light Gray': 

	--->	SAS SUPPORTS HUNDREDS OF COLOURS RANGINF FROM PRIMARY COLOUR-RED TO MORE ESOTERIC COLOURS-LIGRPR(LIGHT GRAYIHS PURPLISH RED).
			THESE COLOURS CAN BE SPECIFIED BY NAME-BLUE OR BY HEXADECIMAL CODE-#0000FF. NAME OF THE COLOUR NEED QUOTATION MARK IF NAME OF 
			IS LONGER THAN 8 CHARACTERS OR CONTAINS EMBEDDED SPACES. RGB HEXADECIMAL CODES BEGINNING WITH A POUND SIGN ALSO REQUIRE 
			QUOTATION MARKS. IF YOU WANT TO SPECIFY COLOURS BY NAME, HERE IS A LIST OF BASIC COLOURS YOU CAN START WITH: AQUA, BLACK, BLUE, FUCHSIA
			GREEN, GRAY, LIME, MAROON, NAVY, OLIVE, PURPLE, RED, SILVER, TEAL, WHITE, YWLLOW.

	--->	BACKGROUND COLOUR -- THE "BCOLOR=" option SPECIFIES A BACKGROUND COLOUR. THIS STATEMENT USES AN RGB HEXADECIMAL CODE: 
					TITLE BCOLOR='#C0C0C0' 'This Title Has a Gray Background':

	--->	HEIGHT -- TO CHANGE THE HEIGHT OF THE TEXT, USE THE "HEIGHT=" OPTIONS WHERE THE VALUE OF "HEIGHT" IS A NUMBER WITH UNITS OF PT, IN OR CM.
			THIS STATEMENT.
					TITLE HEIGHT=12PT 'Small  ' HEIGHT=.25IN 'Medium  ' HEIGHT=1CM 'Large':

	--->	JUSTIFICATION -- YOU CAN CINTROL JUSTIFICATION OF TEXT USING THE "JUSTIFY=" OPTION WHICH CAN HAVE THE VALUE "LEFT", "CENTER", OR "RIGHT".
			YOU CAN EVEN MIX THESE OPTIONS WITHIN A SINGLE STATEMET. THIS STATEMENT
					TITLE JUSTIFY=LEFT 'Left ' JUSTIFY=CENTER 'vs. ' JUSTIFY=RIGHT 'Right':

	--->	FONT -- USE THE "FONT=" OPTION TO SPECIFY A FONT. THIS STATEMENT
					TITLE 'Default   ' FONT=Arial 'Arial '  
						FONT='Times New Roman' 'Times New Roman' FONT=Courier 'Courier':

	--->	BOLD AND ITALIC -- BY DEFAULT, TITLES ARE BOLD. WHEN YOU CHANGE THE FONT, YOU ALSO TURN OFF THE BOLDING. TO TURN ON BOLDING, USE THE
			"BOLD" OPTIONS, TO TURN ON TH ITALICS USE THE "ITALIC" OPTIONS. THERE IS NO OPTION TO TURN OFF THE BOLDING OR ITALICS, SO IF YOU WISH 
			TO TURN THEM OFF, USE THE "FONT=" OPTION. HERE ARE THE THREE OPTIONS TOGETHER,
					TITLE FONT=Courier 'Courier  ' BOLD 'Courier Bold  '  
						ITALIC 'Courier Bold and Italic':


I)	 CUSTOMIZING PROC PRINT WITH THE STYLE= OPTION
	--->	IF YOU WANT TO CHANGE THE OVERALL LOOK OF ANY OUTPUT, YOU CAN CHOOSE A DIFFERENT STYLE TEMEPLATES BY SPECIFYING IT IN A "STYLE=" OPTION
			IN YOUR "ODS" STATEMENT. BUT IF YOU WANT TO CHANGE THE APPEARANCE OF JUST THE HEADERS OR JUST ONE COLUMN OF YOUR OUTPUT. THE REPORTING 
			PROCEDURES, "PRINT", "REPORT" AND "TABULATE", ALLOWS YOU TO CHANGE THE STYLE OF VARIOUS PARTS OF THE TABLE USING THE "STYLE=" OPTION IN
			THE PROCEDURES STATEMENTS.

	--->	THE GENERAL FORM OF THE "STYLE=" OPTION IN THE "PROC PRINT" STATEMENT IS 
					PROC PRINT STYLE(location-list) = {style-attribute = value}: 
							PROC PRINT STYLE(DATA) = {BACKGROUND = pink}:

	--->	YOU CAN HAVE SEVERAL "STYLE=" OPTIONS ON ONE "PROC PRINT" STATEMENT, AND THE SAME STYLE CAN APPLY TO SEVERAL LOCATIONS. HERE ARE SOME
			OF THE LOCATIONS YOU CAN SPECIFY:

							LOCATION						TABLE REGION AFFECTED
							DATA							ALL DATA CELLS
							HEADER							THE COLUMN HEADERS(VRIBALE NAMES)
							OBS								THE DATA IN OBSERVATION COLUMN, OR ID COLUMN IF USING AN ID STATEMENT
							OBSHEADER						THE HEADER FOR THE OBS OR ID COLUMN
							TOTAL							THE DATA IN THE TOTALS ROW PRODUCED BY THE "SUM" STATEMENT
							GRANDTOTAL						THE DATA FOR THE GRANDTOTAL PRODUCE BY THE "SUM" STATEMENT

	--->	IF YOU WANT TO CHANGE THE HEADER OF JUST ONE COLUMN, THEN YOU PUT THE "STYLE=" OPTION IN THE VAR STATEMENT LIKE THIS:
					VAR variable-list / STYLE(location-list) = {style-attribute = value}; 


DATA WORLDRECORD;
INFILE "D:\Practice\SAS\Little SAS Book\Data\World Record.csv" DSD DLM="," FIRSTOBS=2;
INPUT YEAR NAME : $20.	COUNTRY$	TIME$	RECORD$;
RUN;
PROC PRINT DATA = WORLDRECORD;
TITLE "WOMEN'S 50 METER SPEED SKATING";
ID YEAR;
RUN;

PROC PRINT DATA=WORLDRECORD
	STYLE(DATA) = {BACKGROUND = GRAY FOREGROUND = WHITE};
TITLE "WOMEN'S 50 METER SPEED SKATING";
VAR COUNTRY NAME TIME;
VAR RECORD/STYLE(DATA)= {FONT_STYLE = ITALIC JUST = CENTER};
ID YEAR;
RUN;		*

J)	CUSTOMIZING PROC REPORT WITH THE STYLE OPTION
	--->	USING THE "STYLE=" OPTION IN "PROC REPORT" IS SIMILAR TO THE PRINT PROCEDURE BECASUE YOU HAVE TO SPECIFY A LOCATION. THE GENERAL
			FORM OF THE "STYLE=" OPTION IN THE "PROC REPORT" STATEMENT IS  
						PROC REPORT STYLE(location-list) = {style-attribute = value}:
						PROC REPORT DATA = mysales STYLE(HEADER) = {BACKGROUND = GREEN}: 	

	--->	YOU CAN SPECIFY MORE THAN ONE LOCATION IN A SINGLE "STYLE=" OPTION, AND YOU CAN HAVE SEVERAL "STYLE=" OPTIONS IN ONE PROC REPORT
			STATEMENT.

	--->					LOCATION 					TABLE REGION AFFECTED
							HEADER						COLUMN HEADINGS
							COLUMN						DATA CELLS
							SUMMARY						TOTALS CREATED BY "SUMMARIZE" OPTIONS IN "BREAK" OR "REBREAK" STATEMENTS

	--->	IF YOU PUT A "STYLE=" OPTION IN A "PROC REPORT" STATEMENT, THEN IT WILL AFFECT THE WHOLE TABLE, FOR EXAMPLE, ALL THE COLUMN HEADINGS,
			ALL THE DATA CELLS, OR ALL THE SUMMARY BREAKS. YOU CAN CHNGE PART OF A REPORT BY USING THE "STYLE=" OPTION IN OTHER STATEMENTS. TO
			TO SPECIFY A STYLE FOR A PARTICULAR VARIBALE, PUT THE "STYLE=" OPTION IN A DEFINE STATEMENT. IF YOU USE GROUP VARIBALE, YOU MAY WANT
			TO ADD THE "SPANROWS" OPTIONS TO THE PROC STATEMENT. THE SPANROWS OPTIONS COMBINES CELLS IN THE SAME GROUP INTO A SINGLE CELLS. THESE
			STATEMENTS TELLS SAS TO USE MONTH AS A GROUP VARIBALE AND MAKE THE BACKGROUND BLUE FOR BOTH THE HEADER AND DATA:
							PROC REPORT DATA = mysales SPANROWS:
							DEFINE Month / GROUP STYLE(HEADER COLUMN) = {BACKGROUND = BLUE}:

	--->	TO SPECIFY A STYLE FOR PARTICULAR SUMMARY BREAKS, USE THE "STYLE=" OPTION IN A "BREAK" OR "RBREAK" STATEMENT.

	--->	;

DATA SKETTING;
INFILE "D:\Practice\SAS\Little SAS Book\Data\Olympic Speed Skating.csv" DSD DLM="," FIRSTOBS=2;
INPUT NAME : $30.	COUNTRY$	YEARS	MEDALS;
RUN;
PROC REPORT DATA = SKETTING NOWINDOWS;
COLUMN COUNTRY NAME MEDALS;
DEFINE COUNTRY / GROUP;
TITLE "OLYMPIC WOMEN'S SPEED SKETTING";
RUN;

PROC REPORT DATA = SKETTING NOWINDOWS SPANROWS
STYLE (COULMN) = {BACKGROUND = GRAY FOREGROUND = WHITE};
COLUMN COUNTRY NAME MEDALS;
DEFINE COUNTRY / GROUP;
TITLE "OLYMPIC WOMEN'S SPEED SKETTING";
RUN;			*



K)		CUSTOMIZING PROC TABULATE WITH THE STYLE= OPTION
		--->	THE PART OF THE TABLE AFFECTED DEPENDS ON WHERE YOU PLACE THE "STYLE=" OPTION.
			
							STATEMENT 						TABLE REGION AFFECTED
							PROC TABULATE					ALL THE DATA CELLS
							CLASS							CLASS VAIRABLE NAME HEADING
							CLASSLEV						CLASS LEVEL VALUE HEADINGS
							TABLE(CROSSED WITH ELEMENTS)	ELEMENTS DATA CELL
							VAR								ANALYSIS VARIABLE NAME HEADING

		--->	PROC TABULATE STATEMENT --- IF YOU PLACE THE "STYLE=" OPTION ON THE "PROC TABULATE" STATEMENT, ALL THE TABLE'S DATA CELLS WILL HAVE
				THE STYLE. FOR EXAMPLE, IF YOU WANTED ALL THE DATA CELLS IN YOUR TABLE CREATED FROM THE MYSALES SASDATA SET TO HAVE YELLOW BACKGROUND
				THEN YOU WOULD USE THE FOLLOWING STATEMENT:
							PROC TABULATE DATA = mysales STYLE = {BACKGROUND = YELLOW}:

		--->	TABLE STATEMENT --- IF YOU WANT SOME OF THE DATA CELLS TO HAVE A DIFFERENT STYLE FROM THE REST THN YOU NEED TO ADD THE "STYLE=" 
				OPTIONS TO THE TABLE STATEMENT AND CROSS THE STYLE WITH THE VARIABLE OR KEYWORD YOU WANT TO CHANGE
							TABLE City, Month ALL*{STYLE = {BACKGROUND = RED}}:

		--->	CLASSLEV, VAR, and CLASS STATEMENTS --- THE "CLASSLEV", "VAR" AND "CLASS" STATEMENTS ALL REQUIRE THAT YOU PLACE THE "STYLE=" OPTION
				AFTER A SLASH (/). ANY VARIABLE THAT APPEARS IN A "CLASSLEV" STATEMENT MUST ALSO APPERR IN A "CLASS" STATEMENT. FOR EXAMPLE, SUPPOSE
				YOU HAD A TABLE WITH A CLASS VARIABL MONTH, AND YOU WANTED ALL THE VALUES OF MONTH TO HAVE A FOREGROUND COLOUR OF GREEN, THEN YOU
				WOULD USE THE "CLASSLEV" STATEMENT AS FOLLOWS: 
							CLASSLEV Month / STYLE = {FOREGROUND = GREEN}:

		--->	;

DATA OLYMPIC;
INFILE "D:\Practice\SAS\Little SAS Book\Data\World Record Sketting.csv" DSD DLM="," FIRSTOBS=2;
INPUT YEAR$	METERS$	RECORD$;
RUN;
PROC TABULATE DATA = OLYMPIC;
CLASS YEAR RECORD;
TABLE YEAR='', RECORD*N='';
TITLE "MEN'S SPEEDING SKETTING OLYMPIC RECORDS";
RUN;
PROC TABULATE DATA = OLYMPIC 
STYLE = {BACKGROUND = GRAY FOREGROUND = WHITE JUST = CENTER};  
CLASS YEAR RECORD; 
TABLE YEAR = '',RECORD*N = ''; 
TITLE 'Men''s Speed Skating Olympic Records';
RUN;		*


L)		ADDING TRAFFIC LIGHTING TO YOUR OUTPUT
		--->	TRAFFIC-LIGHTING IS A FEATURE THAT ALLOWS YOU TO CONTROL THE STYLE OF CELLS IN THE TABLE BASED ON THE VALUE OF THE DATA IN THE CELL
				THIS WAY YOU CAN DROW ATTENTION TO IMPORTANT VALUES IN YOUR REPORT, OR HIGHLIGHT RELATIONSHIP BETWEEN VALUES. TRAFFIC- LIGHTING CAN 
				BE USED IN ANY THREE REPORTING PROCEDURES: "PRINT", "REPORT" AND "TABULATE".

		--->	TO IMPLANT TRAFFIC-LIGHTING YOU NEED TO DO TWO THINGS. FIRST, CREATE A USER-DEFINED FORMAT SPECIFYING DIFFERENT VALUES FOR THE STYLE
				ATTRIBUTE YOU WANT TO CHANGE OVER THE RANGE IN DATA VALUES. THEN SET THE STYLE ATTRUBUTE EQUAL TO THE FORMAT YOU DEFINED IN THE
				"STYLE=" OPTION. FOR EXAMPLE, IF YOU HAD A FORMAT PROCEDURE THAT CREATED A FORMAT AS FOLLOWS:

							VALUE posneg 
     								LOW -< 0 = 'red' 
     								0-HIGH = 'black':
		--->	THEN IN A VAR STATEMENT IN A "PRINT" PROCDURE, YOU COULD SET THE VALUE OF THE ATTRIBUTE EQUAL TO THE FORMAT IN THE "STYLE=" OPTION
				AS FOLLOWS:
							VAR Balance / STYLE = {FOREGROUND = posneg.};


DATA ATHLETICS;
INFILE "D:\Practice\SAS\Little SAS Book\Data\Top Five Finishers.csv" DSD DLM="," FIRSTOBS=2;
INPUT PLACE NAME : $20.	COUNTRY : $15.	TIME : 7.;
RUN;
PROC PRINT DATA=ATHLETICS;
ID PLACE;
TITLE 'Men''s 5000m Speed Skating';
RUN;

PROC FORMAT; 
VALUE rec 0 -< 378.72 = 'LIGHT GRAY' 
378.72 -< 382.20 = 'VERY LIGHT GRAY' 
382.20 - HIGH = 'WHITE'; 
RUN; 
PROC PRINT DATA = ATHLETICS; 
ID PLACE; 
VAR NAME COUNTRY; 
VAR TIME / STYLE = {BACKGROUND = rec.}; 
TITLE 'Men''s 5000m Speed Skating'; 
RUN; 			*


M)		SELECTED STYLE ATTRIBUTES

				ATTRIBUTE						DESCRIPTION									POSSIBLE VALUE
				BACKGROUND						SPECIFIES THE BACKGOUND COLOUR OF			ANY VALID COLOUR
												THE TABLE OR CELL

				BACKGROUNDIMAGE					SPECIFIES BACKGROUND IMAGE TO BE USED 		ANY GIF, JPEG OR PNG IMAGE FILE
												FOR THE TABLE OR CELL. NOT VALID OF RTF

				FLYOVER							SPECIFIES THE POP-UP TEXT DISPLAYED WHEN	ANY TEXT STRING ENLOCSED IN QUOTATION MARK
												CURSER IS HELD OVER THE TEXT(HTML) OR IF 
												YOU DOUBLE CLICK ON THE TEXT(PDF)

				FONT_FACE						SPECIFIES THE FONT TO USE FOR THE TEXT		ANY VALID FONT(MOST DEVICES SUPPORT TIMES, COURIER,
												IN CELL										ARIAL, AND HELVETICA

				FONT_SIZE						SPECIFIES THE RELATIVE SIZE OF THE FONT		1 TO 7
												FOR THE TEXT IN CELLS

				FONT_STYLE						SPECIFIES THE STYLE OF THE FONT USED IN		ITALIC, ROMAN, or SLANT 
												THE CELL

				FONT_WEIGHT						SPECIFIES THE WEIGHT OF THE FONT USED IN	BOLD, MEDIUM OR LIGHT
												THE CELLS.

				FOREGROUND						SPECIFIES THE COLOUR OF THE TEXT IN THE		ANY VALID COLOUR
												CELLS

				JUST							Specifies the justification of the text 	R|RIGHT, C|CENTER,  
												in the cells.								L|LEFT, or D (decimal) 

				PRETEXT or POSTTEXT				Specifies text that goes either before 		Any text string enclosed in quotation marks 
												(PRETEXT) or after (POSTTEXT) 
												the text in the cells.

				PREIMAGE or POSTIMAGE			Specifies an image that will be				Any GIF, JPEG, or PNG image file 
												inserted either before (PREIMAGE) or		(JPEG and PNG only for RTF) 7
												after (POSTIMAGE) the text in the cells.

				URL								Specifies the URL to link to from the		Any URL 
												text in the cell. HTML, PDF, and 
												RTF only. 
