*
R)	PRODUCING SAMPLE OUPUT WITH PROC RPORT

	--->	THE REPORT PROCEDURE SHARES FEATURES WITH THE PRINT, MEANS, TABULATE and SORT PROCEDURES AND THE DATA STEP. 
			
	--->	    PROC REPORT NOWINDOWS: 
          				COLUMN variable-list:

	--->	IN IT'S SIMPLEST FORM, THE COLUMN STATEMENT IS SIMILAR TO A VAR STATEMENT IN PROC PRINT, TELLING SAS WHICH VARIABLE TO INCLUDE AND IN
			WHAT ORDER. IF YOU LEAVE OUT THE COLUMN STATEMENT, SAS WILL, BY DEFAULT, INCLUDE ALL THE VARIABLES IN YOUR DATASET. IF YOU LEAVE OUT
			NOWINDOWS OPTION, SAS WILL OPEN THE INRERACTIVE REPORT WINDOW.

	--->	NUMERIC vs CHARACTER DATA --- THE TYPE OFREPORT YOU GET FROM PROC REPORT DEPENDS IN PART ON THE TYPE OF DATA YOU USE. IF YOU HAVE AT
			LEAST ONE CHARACTER VARIABL IN YOUR REPORT, THEN, BY DEFAULT YOU WILL GET DETAIL REPORT WITH ONE ROW PER OBSERVATION. IF, ON OTHER
			HAND, YOUR REPORT INCLUDES ONLY NUMERIC VARIABLES, THENM BY DEFAULT, PROC REPORT WILL SUM THOSE VARIABLES. EVEN DATES WILL BE SUMMED,
			BY DEFAULT BECASUE THEY ARE NUMERIC. ;

DATA EMISSION;
INFILE "D:\Practice\SAS\Little SAS Book\Data\emission_annual.csv" DSD DLM="," FIRSTOBS=2;
INPUT Year : 4. State : $3. ProducerType : $30. EnergySource : $30. CO2 : COMMA9. SO2 : COMMA9. Nox : COMMA9. ;
RUN;

PROC REPORT DATA= EMISSION;
TITLE 'Yearly Co2, So2 Nox Emission From Electricity Power Plants';
RUN; 
PROC REPORT DATA= EMISSION;
COLUMN Year State ProducerType CO2 SO2 Nox;
TITLE 'Yearly Co2, So2 Nox Emission From Electricity Power Plants';
RUN; 


PROC REPORT DATA= EMISSION;
COLUMN Year CO2 SO2 Nox;
TITLE 'Yearly Co2, So2 Nox Emission From Electricity Power Plants';
RUN;  *



S)	USING DEFINE STATEMENT IN PROC REPORT

	--->	THE DEFINE STATEMENT IS A GENERAL PURPOSE STATEMENT THAT SPECIFIES OPTIONS FOR AN INDIVIDUAL VARIABLE. YOU CAN HAVE A DEFINE STATEMENT
			FOR EVERY VARIBALE, BUT YOU ONLY NEED TO HAVE A DEFINE STATEMENT IF YOU WANT TO SPECIFY AN OPTION FOR THAT PARTICULAR VARIABLE. THE
			GENERAL FORM OF DEFINE STATEMENT IS
			
					DEFINE Variable / options 'Column-header':

	--->	USING OPTIONS  -- USAGE OPTIONS THE MOST IMPORTANT OPTION IS A USAGE OPTION THAT TELLS SAS HOW THAT VARIABLE IS TO BE USED.
			POSSIBLE VALUE OF USAGE OPTIONS INCLUDE:

					ACROSS						CREATES A COLUMN FOR EACH UNIQUE VLAUE OF THE VARIABLE

					ANALYSIS					CALCULATES STATISTICS FOR THE VARIABLE. THIS IS THE DEFAULT USAGE FOR NUMERIC
												VARIABLES, AND THE DEFAULT STATISTICS IN SUM. 

					COMPUTED					CREATES A NEW VARIABLE WHOSE VALUE YOU CALCULATED IN A COMPUTE BLOCK.

					DISPLAY						CREATES ONE ROW FOR EACH OBSERVATION IN THE DATA SET. THIS IS DEFAULT
												USE FOR CHARACTER VARIABLES.
			
					GROUP						CREATES ONE ROW FOR EACH UNIQUE VALUE OF THE VARIABLE.

					ORDER						CREATES ONE ROW FOR EACH OBSERVATION WITH ROW ARRANGED ACCORDING TO THE VALUES
												OF THE ORDER VARIABLE


	--->	CHANGING COLUMN HEADERS --- THERE ARE SERVERAL WAYS TO CHANGE COLUMN HEADERS IN "PROC REPORT" INCLUING USING A "LABEL" STATEMENT
			AS DESCRIBED IN SECTION. OR SPECIFYING A COLUMN HEADER IN DEFINE STATEMENT. THE FOLLOWING STATEMENTS TELLS SAS TO ARRANGE A REPORT
			BY THE VALUES OF THE VARIABLE AGE, AND USE THE WORDS "AGE OF ADMISSION" AS THE COLUMN HEADER FOR THAT VARIABLE. PUTTING A SLASH IN
			A COLUMN HEADER TELLS SAS TO SPLIT THE HEADER AT THAT TIME.

					DEFINE Age / ORDER 'Age at/Admission':

	--->	MISSING DATA -- BY DEFAULT OBSERVATIONS AS EXCLUDED FROM REPORTS IF THEY HAVE MISSING VALUES FOR VARIABLES LISTED IN ORDER, GROUP
			OR ACROSS STATEMENTS. IF YOU WANT TO KEEP THOSE OBSERVATIONS, THEN SIMPLY ADD THE "MISSING" OPTION TO YOUR "PROC" STATEMENT LIKE THIS.;

DATA EMISSION;
INFILE "D:\Practice\SAS\Little SAS Book\Data\emission_annual.csv" DSD DLM="," FIRSTOBS=2;
INPUT Year : 4. State : $3. ProducerType : $30. EnergySource : $30. CO2 : COMMA9. SO2 : COMMA9. Nox : COMMA9. ;
RUN;

PROC REPORT DATA=EMISSION;
COLUMN Year State CO2;
DEFINE CO2 / ORDER;
DEFINE CO2 / ANALYSIS 'CO2';
TITLE 'CO2 EMISSION PER YEAR BY STATE';
RUN;


DATA PARK;
INFILE "D:\Practice\SAS\Little SAS Book\Data\National Park.csv" DSD DLM="," FIRSTOBS=2;
INPUT NAME : $20. TYPE : $5. REGION : $6. MUSEUMS_NUMBER CAMPGROUND;
RUN;
PROC REPORT DATA=PARK MISSING;
COLUMN REGION NAME TYPE MUSEUMS_NUMBER CAMPGROUND;
DEFINE REGION / ORDER;
DEFINE CAMPGROUND / ANALYSIS 'CAMPING';
TITLE 'NATIONAL PARK DETAILS';
RUN;    


LIBNAME NANDAN "D:\Practice\SAS\Little SAS Book\Practice";
DATA NANDAN.EMISSION_ANUAL;
INFILE "D:\Practice\SAS\Little SAS Book\Data\emission_annual.csv" DSD DLM="," FIRSTOBS=2;
INPUT Year : 4. State : $3. ProducerType : $30. EnergySource : $30. CO2 : COMMA9. SO2 : COMMA9. Nox : COMMA9. ;
RUN;



DATA NANDAN.ANNUAL_GENERATION_STATE;
INFILE "D:\Practice\SAS\Little SAS Book\Data\annual_generation_state.csv" DSD DLM="," FIRSTOBS=5;
INPUT YEAR : 4. STATE : $3. TYPE_OF_PRODUCER : $30. ENERGY_SOURCE : $30. GENERATION : COMMA9.;
RUN;


DATA NANDAN.GENERATE_MONTHLY;
INFILE "D:\Practice\SAS\Little SAS Book\Data\generation_monthly.csv" DSD DLM="," FIRSTOBS=6;
RUN;


*


T)	CREATING SUMMARY REPORT WITH PROC REPORT

	--->	TWO DIFFERENT USAGE TYPES CAUSE THE REPORT PROCEDURE TO "ROLL UP" DATA INTO SUMMARTY GROUPS BASED ON THE VALUES OF VARIABLES. 
			WHILE THE GROUP USAGE TYPE PRODUCES SUMMARY ROWS, THE ACORSS USAGE TYPE PRODUCES SUMMARY COLUMN.

	--->	GROUP VARIABLES --- DEFINING A GROUP VARIABLE IS FAIRLY SIMPLE. JUST SPECIFY THE GROUP USAGE OPTION IN A DEFINE STATEMENT. BY DEFAULT
			ANALYSIS VARIABLES WILL BE SUMMED. TH FOLLOWING PROC REPORT TELLS SAS TO PRODUCE A REPORT SHOWING THE SUM OF SALARY AND OF BONUS WITH
			A ROW FOR EACH VALUE OF DEPARTMENT.

	--->	PROC REPORT DATA = EMPLOYEES NOWINDOWS:
			COLUMN DEPARTMENT SALARY BONUS:
			DEFINE DEPARTMENT / GROUP:

	--->	ACROSS VARIABLE ---  TO DEFINE AN ACROSS VARIABLE, YOU ALSO USE A DEFINE STATEMENT. HOWEVER, BY DEFAULT SAS PRODUCES COUNTS RATHER
			THAN SUMS. TO OBTAIN SUMS FOR ACROSS VARIABLE, YOU MUST TELL SAS WHICH VARIABLE TO SUMMARISE. YOU DO THAT BY PUTTING A COMMA BETWEEN
			THE ACORSS VARIABLE AND ANALYSIS VARIABLE(OR VARIABLE IF YOU ENLCOSE THEM IN PARENTHESES). THE FOLLOWING PROC REPORT TEELS SAS TO
			PRODUCE A REPORT SHOWING THE SUM OF SALARY AND OF BONUS WITH ONE COLUMN FOR EACH VALUE OF DEPARTMENT.

	--->	PROC REPORT DATA = employees NOWINDOWS: 
			COLUMN Department , (Salary Bonus):
			DEFINE Department / ACROSS;  

DATA PARK2;
INFILE "D:\Practice\SAS\Little SAS Book\Data\National Park.csv" DSD DLM="," FIRSTOBS=2;
INPUT NAME : $20. TYPE : $5. REGION : $6. MUSEUMS_NUMBER CAMPGROUND;
RUN;
PROC REPORT DATA=PARK2;
COLUMN TYPE REGION MUSEUMS_NUMBER CAMPGROUND;
DEFINE REGION / GROUP;
TITLE 'NATIONAL PARK';
RUN;


PROC REPORT DATA=PARK2;
COLUMN TYPE REGION MUSEUMS_NUMBER CAMPGROUND;
DEFINE REGION / GROUP;
DEFINE TYPE / ACROSS;
TITLE 'NATIONAL PARK';
RUN;
PROC REPORT DATA=PARK2;
COLUMN REGION TYPE , (MUSEUMS_NUMBER CAMPGROUND);
DEFINE REGION / GROUP;
DEFINE TYPE / ACROSS;
TITLE 'NATIONAL PARK';
RUN;   *


U) ADDING SUMMARY BREAK TO PROC REPORT OUPUT

	--->	TWO KIND OF STATEMENT ALLOWS YOU TO INSERT BREAKS INTO REPORT. THE "BREAK" STATEMENT ADDS A BREAK TO EAH UNIQUE VALUE OF THE VARIABLE
			YOU SPECIFY, WHILE THE "RBREAK" STATEMENT DOES THE SAME FOR THE ENTIRE REPORT(OR BY-GROUP IF YOU USING A BY STATEMENT). THE GENERAL 
			FORMS OF THESE STATEMENTS ARE
			
						BREAK Location Variable / Options:
						RBREAK Location / Options:

	--->	WHERE LOCATION HAS TWO POSSIBLE VALUES. "BEFORE" or "AFTER" DEPENDING ON WHETHER YOU WANT THE BREAK TO PRECEDE OR FOLLO THAT PARTICULAR
			SECTION OF THE REPORT. THE OPTIONS THAT COME AFTER THE SLASH TELL SAS WHAT KIND OF BREAK TO INSERT. SOME OF THE POSSIBLE OPTIONS ARE

						PAGE 					starts a new page
						SUMMARIZE 				inserts summary statistics for numeric variables

	--->	NOTICE THAT "BREAK" STATEMENT REQUIRES YOU TO SPECIFY A VARIABLE, BUT THE "RBREAK" STATEMENT DOESN'T.

	--->	YOU CAN USE AN "RBREAK" STATEMENT IN ANY REPORT, BUT YOU CAN USE "BREAK" ONLY IF YOU HAVE AT LEAST ONE GROUP OR ORDER VARIABLE.

	--->	;


DATA PARK3;
INFILE "D:\Practice\SAS\Little SAS Book\Data\National Park.csv" DSD DLM="," FIRSTOBS=2;
INPUT NAME : $20. TYPE : $5. REGION : $6. MUSEUMS_NUMBER CAMPGROUND;
RUN;
PROC REPORT DATA=PARK3;
COLUMN NAME REGION MUSEUMS_NUMBER CAMPGROUND;
DEFINE REGION / ORDER;
BREAK AFTER REGION / SUMMARISE;
RBREAK AFTER / SUMMARISE;
TITLE "DETAILED REPORT WITH SUMMARY BREAK";
RUN;			*


V)	ADDING STATISTICS TO PROC REPORT OUTPUT
	--->	THERE ARE SEVERAL WAYS TO REQUEST STATISTICS IN THE REPORT PROCEDURE. AN EASY METHOD IS TO INSERT STATISTICS KEYWORDS DIRECTLY INTO
			A "COLUMN" STATEMENT ALONG WITH THE VARIABLE NAMES. THIS IS A LITTLE LIKE REQUESTING STATISTICS IN A "TABLE" STATEMENT IN PROC "TABULATE"
			EXCEPT THAT INSTEAD OF USING AN ASTERISK TO CROSS A STATISTICS KEYWORD WITH A VARIABL, YOU USE A COMMA. IN FACT, "PROC REPORT" CAN 
			PRODUCE ALL THE SAME STATISTICS AS "PROC TABULATE" AND "PROC MEANS" BECASUE IT USES THE DAME INTERNAL ENGINE TO COMPUTE THOSE STATISTICS.
			

	--->				MAX						HIGHEST VALUE
						MIN						LOWEST VALUE
						MEAN					ARTHEMETIC MEAN
						MEDIAN					MEDIAN
						MODE					MODE
						N						NUMBER OF NON-MISSING VALUES
						NMISS					NUMBER OF MISSING VALUES
						PCTN					PERCENTAGE OF OBSERVATION FOR THAT GROUP
						PCTSUM					PERCENTAGE OF A TOTAL SUM REPERSENTED BY THAT GROUP
						STD						STANDARD DEVIATION
						SUM						SUM

	--->	APPLYING STATISTICS TO VARIABLES ---- TO REQUEST A STATISTICS FOR A PARTICULAR VARIABLE, INSERT A COMMA BETWEEN THE STATISTICS AND 
			VARIABLE IN THE "COLUMN" STATEMENT. ONE STATISTICS, "N", DOES NOT REQUIRE A COMMA BECASUE IT DOES NOT APPLY TO A PARTICULAR VARIABLE. 
			IF YOU INSERT "N" IN A "COLUMN" STATEMENT, THEN SAS WILL PRINT THE NUMBER OF OBSERVATION THAT CONTRIBUTED TO THAT ROW OF THE REPORT.
			THIS STATEMENT TELLS SAS TO PRINT TWO COLUMNS OF DATA: THE MEDIAN OF A VARIABLE NAME AGE, AND THE NUMBER OF OBSERVATION IN THAT ROW.

				COLUMN Age,MEDIAN N:

	--->	TO REQUEST MULTIPLE STATISTICS OR STATISTICS FOR MULTIPLE VARIABLE, PUT PARENTHESIS AROUND THE STATISTICS OR VARIABLES. THE STATEMENT
			USES PARENTHESE TO REQUEST TWO STATISTICS FOR THE VARIABLE AGE, AND THEN REQUESTS ONE STATISTICS FOR TWO VARIABLE HEIGHT & WEIGHT.

				COLUMN Age,(MIN MAX) (Height Weight),MEAN:

	--->	;


DATA PARK4;
INFILE "D:\Practice\SAS\Little SAS Book\Data\National Park.csv" DSD DLM="," FIRSTOBS=2;
INPUT NAME : $20. TYPE : $5. REGION : $6. MUSEUMS_NUMBER CAMPGROUND;
RUN;


PROC REPORT DATA= PARK4;
COLUMN REGION TYPE N (MUSEUMS_NUMBER CAMPGROUND),MEAN;
DEFINE REGION / GROUP;
DEFINE TYPE / GROUP;
TITLE 'NATIONAL PARKS STATISTICAL ANALYSIS';
RUN;


PROC REPORT DATA= PARK4;
COLUMN REGION N TYPE (MUSEUMS_NUMBER CAMPGROUND),MEAN;
DEFINE REGION / GROUP;
DEFINE TYPE / ACROSS;
TITLE 'NATIONAL PARKS STATISTICAL ANALYSIS';
RUN;		*


W)	ADDING COMPUTED VRIABLES TO PROC REPORT OUTPUT
	--->	UNLIKE MANY PROCEDURES, THE "REPORT" PROCEDURE HAS THE ABILITY TO COMPUTE NOT ONLY STATISTICS (LIKE SUMS AND MEANS) BUT ALSO NEW
			VARIABLES. YOU DO THIS BY USING A COMPUTE BLOCK. COMPUTE BLOCKS START WITH A "COMPUTE" STATEMENT AND ENDS WITH AN "ENDCOMP" STATEMENT.

	--->	IN BETWEEN YOU PUT THE PROGRAMMING STATEMENTS TO CALCULATE YOUR NEW VARIABLE. "PROC REPORT" USES A LIMITED SET OF PROGRAMMING
			STATEMENT INCLUDING ASSINGEMENT STATEMENTS, "IF-THEN/ELSE" STATEMENTS AND "DO" LOOP, YOU DO NOT HAVE TO SPECIFY A "DEFINE" STATEMENT
			FOR THE NEW VARIABLE, BUT IF YOU DO, THEN GIVE IT A USAGE TYPE OF "COMPUTED". 

	--->	THE GENERAL SYNTAX FOR THESE STATEMENT IS 
			
				DEFINE new-var-name / COMPUTED:
					COMPUTE new-variable-name / Options:
						programming statements
				ENDCOMP:

	--->	COMPUTING NUMERIC VARIABLES -- FOR A NUMERIC VARIABLE, SIMPLY NAME THE NEW VARIABLE IN THE "COMPUTE" STATEMENT. IF YOU USE ANY
			VARIABLES WITH A TYPE OF ANALYSIS IN THE COMPUTE BLOCK, YOU MUST APPEND THE VARIABLE NAME WITH IT'S STATISTICS. THE DEFAULT
			STATISTICS FOR AN ANALYSIS VARIABLE IS "SUM". THE FOLLWOING STATEMENT COMPUTE A VARIABLE NAMED INCOME BY ADDING SALARY AND 
			BONUS 

				DEFINE Income / COMPUTED:
				COMPUTE iNCOME:
					Income=Salary.Sum + Bonus.Sum
				ENDCOMP:

	--->	COMPUTING CHARACTER VARIABLES ---	FOR A CHARACTER VARIABLES, ADD THE "CHAR" OPTIONS TO THE "COMPUTE" STATEMENT. YOU WILL 
			PROBABLY ALSO WANT THE "LENGTH" OPTION. LENGTHS FOR COMPUTED CHARACTER VARIABLES RANGE FROM 1 TO 200, WITH A DEFAULT FOR 8.
			THE FOLLOWING STATEMENTS COMPUTE A VARIABLE NAMED JOBTYPE UISNG "IF-THEN/ELSE" STATEMENT.

	--->	;


DATA PARK5;
INFILE "D:\Practice\SAS\Little SAS Book\Data\National Park.csv" DSD DLM="," FIRSTOBS=2;
INPUT NAME : $20. TYPE : $5. REGION : $6. MUSEUMS_NUMBER CAMPGROUND;
RUN;
PROC REPORT DATA= PARK5;
COLUMN NAME REGION MUSEUMS_NUMBER CAMPGROUND FACILITIES NOTE;
DEFINE MUSEUMS_NUMBER / ANALYSIS SUM NOPRINT;
DEFINE CAMPING / ANALYSIS SUM NOPRINT;
DEFINE FACILITIES / COMPUTED "CAMPGROUND/AND/MUSEUMS_NUMBER";
DEFINE NOTE / COMPUTED;
COMPUTE FACILITIES;
	FACILITIES= MUSEUMS_NUMBER.SUM + CAMPGROUND.SUM;
ENDCOMP;
COMPUTE NOTE / CHAR LENGTH = 10;
	IF CAMPGROUND.SUM = 0 THEN NOTE = "NO CAMPING";
ENDCOMP;
TITLE 'REPORT WITH TWO COMPUTED VARIABLE';
RUN;				*


X)	GROUPING DATA IN PROCEDURES WITH USER-DEFINED FORMATS

	--->	WITH USE DEFINED FORMATS YOU CAN GROUP DATA IN PROCEDURE OUTPUT WITHOUT CREATEING A NEW VARIABLE. THIS IS HANDY FOR CASES WHERE YOU HAVE
			A LOT OF DATA, AND IT TAKES LONG TIME TO RUN A DATA STEP. 

	--->	ALSO USING THIS METHOD IT IS EASY TO CHANGE GROUPING BY SIMLY CREATING A NEW FORMAT. THIS METHOD WORKS FOR PROCEDURES THAT GROUPS
			THE DATA SUCH AS "PROC FREQ", "PROC TABULATE", "PROC MEANS", WITH A "CLASS" STATEMENT, AND "PROC REPORT" WITH "GROUP" OR "ACROSS"
			VARIABLES.

	--->	GROUPING DATA THAT WAY IS A TWO-STEP PROCESS. FIRST USE THE "FORMAT" PROCEDURE TO DEFINE A FORMATE ASSIGNS ALL THE VALUES THAT YOU WANT
			TO GROUP TOGETHER TO A TEXT STRING. SECOND, USE THE "FORMAT" STATEMENT IN THE PROCEDURE TO ASSIGN THE FORMAT TO THE VARIABLE TO BE
			GROUPED.

	--->	;


DATA BOOKS;
INFILE "D:\Practice\SAS\Little SAS Book\Data\Library Data By Age And Fiction Preference.csv" DSD DLM="," FIRSTOBS=2;
INPUT AGE TYPE$;
RUN;
PROC FORMAT;
	VALUE AGEGROUP 
		0-18= '0 TO 18'
		19-25= '19 TO 25'
		26-49= '26 TO 49'
		50-HIGH = '50+';
	VALUE AGEGROUPS
		0-25= '0 TO 25'
		26-HIGH= '26 +';
	VALUE $BOOKTYPE
		'Bio', 'Non','Ref' = 'Non- Fictional'
		'Fic','Mys','Sci'= 'Fiction';
RUN;
PROC FREQ DATA=BOOKS;
	TITLE 'PATRON AGE BY BOOK TYPE: FOUR AGE GROUP';
	TABLE TYPE * AGE / NOPERCENT NOROW NOCOL;
	FORMAT AGE AGEGROUP. TYPE $BOOKTYPE.;
RUN;

PROC FREQ DATA= BOOKS;
	TITLE 'PATERON AGE BY BOOK TYPE';
	TABLES TYPE * AGE / NOPERCENT NOROW NOCOL;
	FORMAT AGE AGEGROUPS. TYPE $BOOKTYPE. ;
RUN;
