*
A)	EXAMING THE DISTRIBUTION OF DATA WITH PROC UNIVARIATE

	--->	WHEN YOU DO STATISTICAL ANALYSIS, YOU USUALLY HAVE GOAL IN MIND, A QUESTION YOU ARE TRYING TO ANSWER, OR A HYPOTHESES YOU WANT TO TEST.
			BUT BEFORE YOU JUMP INTO STATISTICAL TESTS, IT IS A GOOD IDEA TO PAUSE AND DO A LITTLE EXPLORATION. A GOOD PROCEDURE TO USE AT THIS 
			POINT IS PROC UNIVARIATE.

	--->	PROC UNIVARIATE, WHICH IS A PART OF BASE SAS SOFTWARE, PRODECES STATISTICAS AND GARPHS DESCRIBING THE DISTRIBUTION OF A SINGLE VARIABLE
			THE STATISTICS INCLUDES THE MEAN, MEDIAN, MODE STANDARD DEVIATION SKEWNESS AND KURTOSIS.

	--->	USING PROC UNIVARIATE IS FAIRLY SIMPLE. AFTER THE PROC STATEMENT, YOU SPICIFY ONE OR MORE NUMERIC VARIABLES IN A VAR STATEMENT;

							PROC UNIVARIATE;
								VAR var-list;

*	--->	WITHOUT A VAR STATEMENT SAS WILL CALCULATE THE STATISTICS FOR ALL NUMERIC VARIABLES IN YOUR DATA SET. YOU CAN SPECIFY OTHER OPTIONS
			IN THE PROC STATEMENT. IF YOU WISH SUCH AS NORMAL WHICH PRODECES TESTS OF NORMALITY;


							PROC UNIVARIATE NORMAL;


DATA STATISTICS;
INFILE "D:\Practice\SAS\Little SAS Book\Data\Statistics Class.csv" DSD DLM=",";
INPUT SCORE;
RUN;
PROC UNIVARIATE DATA =STATISTICS;
VAR SCORE;
TITLE;
RUN;	*


B)	CREATING STATISTICAL GRAPHICS WITH PROC UNIVAIATE

	--->	THE "UNIVARIATE" PROCEDURE SEVERAL GRAPHS THAT ARE USEFUL FOR DATA EXPLORATION. FOR EXAMPLE, HISTOGRAMS ARE A GOOD WAY TO VISUALIZE
			THE DISTRIBUTION OF A VARIABLE, WHILE PROBABILITY AND QUANTILE-QUANTILE PLOTS CAN SHOW HOW DATA COMPARE TO THEORERICAL DISTRIBUTIONS
			TO PRODUCE THESE GRAPHS, INCLUDE THE DESIRED PLOT REQUEST STATEMENT. HERE IS THE GENERAL FORM OF PROC UNIVARIATE WITH PLOT REQUESTS;

							PROC UNIVARIATE;
							VAR variable-list;
							Plot-request variable-list / options;
							RUN;

*	--->	PLOT REQUESTS -- THE FOLLOWING GRAPHS CAN BE CREATED WITH PROC UNIVARIATE:

							CDFPLOT						REQUESTS A CALMULATIVE DISTRIBUTION FUNCTION PLOT
							HISTOGRAM					REQUESTS A HISTOGRAM
							PPPLOT						REQUESTS A PROBABILITY-PROBABILITY PLOT
							PROBPLOT					REQUEST A PROBABILITY PLOT
							QQPLOT						REQUEST A QUANTILE-QUANTIL PLOT;


PROC UNIVARIATE DATA= STATISTICS;
VAR SCORE;
HISTOGRAM SCORE / NORMAL;
PROBPLOT SCORE;
TITLE;
RUN; 		*


C)	PRODUCING STATISTICS WITH PROC MEANS

	--->	MOST OF THE DISCRIPTIVE STATISTICS THAT PRODUCE WITH PROC UNIVARIATE YOU CAN ALSO PRODUCE WITH PROC MEANS. UNIVARIATE IS USEFUL WHEN 
			YOU WANT AN INDEPTH STATISTICAL ANANLYSIS OF DATA DISTRIBUTION. BUT IF YOU KNOW YOU WANT ONLY A FEW STATISTICS, THEN MEANS IS A 
			BETTER WAY TO GO. WITH MEANS YOU CAN ASK FOR JUST THE STATISTICS YOU WANT. THE MEANS POCEDURE DOES NOT PRODUCE ANY ODS GRAPHICS.

	--->	THE MEANS PROCEDURE REQUIRES ONLY ONE STATEMENT:

	--->			CLM			TWO SIDED CONFIDENCE LIMITS					RANGE 				THE RANGE
					CSS			CORRECTED SUM OF SQUARES					SKEWNESS			SKEWNESS
					CV			COEFFICIENT OF VARIATION					STDDEV				STANDARD DEVIATION
					KURTOSIS	KURTOSIS									STDERR				STANDARD ERROR OF MEANS
					LCLM		LOWER CONFIDENCE LIMIT						SUM					THE SUM
					MAX			MAXIMUM VALUE								SUMWGT				SUM OF WEIGHTED VARIABLES
					MEAN		MEAN										UCLM				UPPER CONFIDENCE LIMIT
					MIN			MINIMUM VALUE								USS					UNCORRECTED SUM OF SQUARES VARIANCE
					MODE		MODE										VAR					VARIANCE
					N			NUMBER OF NON MISSING VALUE					PROBT				PROBABILITY FOR STUDENT'S t
					NMISS		NUMBER OF MISSING VALUE						T					STUDENT'S t 
					MEDIAN(P50)	MEDIAN										Q3(P75)				75% QUANTILE
					Q1(P25)		25% QUANTILE								P5					5% QUANTILE
					P1			1%	QUANTILE								P90					90% QUANTILE
					P10			10%	QUANTILE								P99					99% QUANTILE
					P95			95% QUANTILE

	--->	CONFIDENCE LIMIT- THE DEFAULT CONFIDENCE LEVEL FOR THE CONFIDENCE LIMITS IS 0.05 OR 95%. IF YOU WANT A DIFFERENT CONFIDENCE LEVEL, 
			THEN REQUEST IT WITH "ALPHA=" OPTION IN THE PROC MEANS STATEMENT. FOR EXAMPLE, IF YOU WANT 90% CONFIDENCE LIMITS, THEN SPECIFIY 
			"ALPHA=.10" ALONG WITH CLM OPTION. THEN THE "PROC MEANS" STATEMENT WOULD LOO LIKE THIS;

								PROC MEANS ALPHA = .10 CLM;

*	--->	VAR STATEMENT -- BY DEFAULT MEANS WILL PRODUCE STATISTICS FOR ALL NUMERIC VARIABLES IN YOUR DATA SET. IF YOU DO NOT WANT ALL THE
			VARIABLES, THEN SPECIFY THE ONES YOU WANT IN THE VAR STATEMENT. ;

								PROC MEANS options; 
   								VAR variable-list; 



DATA BOOKLENGTHS;
INFILE "D:\Practice\SAS\Little SAS Book\Data\Author Of Children’s Books.csv" DSD DLM=",";
INPUT NUMBERSOFPAGES @@;
RUN;
PROC MEANS DATA = BOOKLENGTHS N MEAN MEDIAN CLM ALPHA = .10;
TITLE "SUMMARY OF PICTURE BOOK LENGTH";
RUN;			*


D)	TESTING MEANS WITH PROC TTEST

	--->	AS YOU WOULD EXPECT FROM IT'S NAME, THE TTEST PROCEDURE, WHICH IS PART OF SAS/STAT SOFTWARE, COMPUTES t TEST. YOU YSE t TEST WHEN YOU 
			WANT TO COMPARE MEANS. SUPPOSE, FOR EXAMPLE, THAT A STATISTICS INSTRUCTOR SELECTED A RANDOM SAMPLE OF STUDENTS TO HAVE EXTRA TUTORING.
			SHE COULD TEST WHETHER THE TRUE MEAN OF THEIR SCORES WAS ABOVE SPECIFIC LEVEL (CALLED A SAMPLE TEST), SHE COULD COMPARE THE SCORES OF 
			STUDENTS WHO HAD TUTORING TO THOSE WHO DIDN'T (A TWO INDEPENDENT SAMPLE TEST), AND SHE COULD COMPARE THE SCORES OF STUDENTS BEFORE 
			AND AFTER TUTIRING( A PAIRED TEST). PROC TTEST PERFORMS ALL THESE TYPES OF TESTS.

	--->	ONE SAMPLE COMPARISONS -- TO COMPUTE A t TEST FOR SINGLE MEAN, YOU LIST THAT VARIABLE IN A VAR STATEMENT. SAS WILL TEST WHETHER THE
			MEAN IS SIGNIFICANTLY DIFFERENT FROM H0, A SPECIFIED NULL VALUE. THE DEFAULT VALUE OF H0 IS ZERO. YOU CAN SPECIFY THE DIFFERENCE VALUE
			USING THE H0=OPTION.;


							PROC TTEST H0 = n options;
							VAR variable;

*	--->	TWO INDEPENDENT SAMPLE COMPARISIONS -- TO COMPARE TWO INDEPENDENT GROUPS, YOU USE A "CLASS" AND "VAR" STATEMENT. IN THE "CLASS"
			STATEMENT, YOU LIST THE VARIABLE THAT DISTINGUISHES THE TWO GROUPS. IN THE "VAR" STATEMENT, YOU LIST THE RESPONSE VARIABLE.;

							PROC TTEST options;
							PAIRED variable1 * variable2;

*	--->	HERE ARE THE FEW OPTIONS AVAIABLE.

							ALPHA = n				SPECIFIES THE LEVEL FOR THE CONFIDENCE LIMITS. THE VALUE OF N MUST BE BETWEEN 0 
													(100% CONFIDENCE) AND 1 (0% CONFIDENCE). THE DEFAULT IS  0.05 (95% CONFIDENCE 
													LIMITS). 


							CI = type				SPECIFIES THE TYPE OF CONFIDENCE INTERVAL FOR THE STANDARD DEVIATION. IF YOU 
													DON'T SPECIFY THIS OPTION, THEN BY DEFAULT THE VALUE OF TYPE IS EQUAL WHICH 
													PRODUCES AN EQUAL-TAILED CONFIDENCE INTERVAL. OTHER POSSIBLE VALUES ARE 
													UMPU FOR AN INTERVAL BASED ON THE UNIFORMLY MOST POWERFUL UNBIASED TEST, 
													AND NONE TO REQUEST NO CONFIDENCE INTERVAL FOR THE STANDARD DEVIATION.

							H0  n					REQUESTS A TEST OF THE HYPOTHESIS H0 = N. THE DEFAULT VALUE IS 0. 

							NOBYVAR					MOVES THE NAMES OF THE VARIABLES  FROM THE TITLE TO THE OUTPUT TABLE.

							SIDES = type			SPECIFIES WHETHER THE P-VALUE AND CONFIDENCE INTERVAL ARE ONE OR TWO-TAILED. 
													POSSIBLE VALUES OF TYPE ARE 2 (THE DEFAULT) FOR TWO-TAILED, L (FOR A LOWER ONE
													SIDED TEST) OR U (FOR AN UPPER ONE-SIDED TEST). ;



DATA RACE;
INFILE "D:\Practice\SAS\Little SAS Book\Data\Finishing Times For Semifinal And Final Races.csv" DSD DLM=",";
INPUT SWIMMER$	FINALTIME	SEMIFINALTIME @@;
RUN;
PROC TTEST DATA = RACE;
TITLE '50m Freestyle Semifinal vs. Final Results';
PAIRED SEMIFINALTIME * FINALTIME;
RUN;	*


E)	CREATING STATISTICAL GRAPHICS WITH PROC T-TEST

	--->	THE "TTEST" USES ODS GRAPHICS TO PRODUCE SEVER PLOTS THAT HELP YOU VISUALIZE YOUR DATA INCLUDING HISTOGRAMS, BOX PLOTS, AND Q-Q PLOTS. 
			MANY PLOTS ARE GENERATED BY DEFAULT, BUT YOU CAN CONTROL WHICH PLOTS ARE CARETED USING THE "PLOTS" OPTION ON THE "PROC TTEST" STATEMENT.
			HERE IS THE GENERAL FORM OF THE "RPOC TTEST STATEMENT" WITH PLOT OPTIONS;

								PROC TTEST PLOTS = (plot-request-list);

*	--->	PLOT REQUEST -- THE PLOST AVAILABEL TO YOU DEPENDS ON THE TYPE OF COMPARISON YOU REQUEST. HERE ARE PLOTS YOU CAN REQUEST FOR ONE SMAPLE,
			TWO SAMPLE, AND PAIRED t TESTS.

	--->				ALL							REQUESTS ALL APPROPRIATE PLOTS
						BOXPLOT						CREATES BOX PLOTS
						HISTOGRAM					CREATES HISTOGRAMS OVERLAID WITH NORMAL AND KERNAL DENSITY CUREVE
						INTERVALPLOT				CREATES PLOT OF CONFIDENCE INTERVAL PLOT
						NONE						SURPESSES ALL PLOTS
						QQPLOTS						CREATES A NORMAL QUANTILE-QUANTILE PLOT
						SUMMARYPLOT					CREATES ONE PLOT THAT INCLUDES BOTH HISTOGARM AND SUMMARY PLOTS.

	--->	THE FOLLOWING PLOST OF ALSO AVAILABLE FOR PAIR t TESTS:

						AGREEMENTPLOT				CREATES AGREEMENT PLOT
						PROFILESPLOT				CREATES A PROFILE PLOT

	--->	EXCLUDING AUTOMATIC PLOTS -- BY DEFAULT THE "QQPLOTS" AND "SUMMARYPLOT"  PLOTS ARE GENERATED AUTOMATICALLY FOR ONE SAMPLE, TWO SAMPLE,
			AND PAIRED t TESTS. FOR PAIRED t TESTS, THE "AGREEMENTPLOT" and "PROFILESPLOT" ARE GNERATED BY DEFAULT. IF YOU CHOOSE SPECIFIC PLOTS
			IN THE PLOT-LIST, THE DEFAULT PLOTS WILL STILL BE CREATED UNLESS YOU ADD THE "ONLY" GLOBAL OPTION;

								PROC TTEST PLOTS(ONLY) = (plot-request-list);


PROC TTEST DATA = RACE PLOTS(ONLY) = (SUMMARYPLOT QQPLOT);
TITLE '50m Freestyle Semifinal vs. Final Results';
PAIRED SEMIFINALTIME * FINALTIME;
RUN;		*


F)	TESTING CATEGORICAL DATA WITH PROC FREQ

	--->	"PROC FREQ", WHICH IS PART OF BASE SAS SOFTWARE, PRODUCES MANY STATISTICS FOR CATEGORICAL DATA. THE BEST KNOWN OF THESE IS CHI-SQUARE.
			ONE OF THE MOST COMMON FREQ IS TO TEST THE HYPOTHESIS OF NO ASSOCIATION BETWEEN TWO VARIABLES. ANOTHER USE IS TO COMPUTE MEASURES OF 
			ASSOCIATION, WHICH INDICATE THE STRENGTH OF THE RELATIONSHIP BETWEEN THE VARIABLE. THE BASIC FORM OF "PROC FREQ" IS;

								PROC FREQ; 
								TABLES variable-combinations / options;

*	--->	OPTIONS - HERE ARE A FEW OF STATISTICAL OPTIONS AVAILABLE.

						AGREE						REQUESTS TESTS AND MEASURES OF CLASSIFICATION AGREEMENT INCLUDING MCNEMAR’S 
													TEST, BOWKER’S TEST, COCHRAN’S Q TEST, AND KAPPA STATISTICS. 

						CHISQ						REQUESTS CHI-SQUARE TESTS OF INDEPENDENCE AND MEASURES OF ASSOCIATION

						CL							REQUESTS CONFIDENCE LIMITS FOR MEASURES OF ASSOCIATION

						CMH							REQUESTS COCHRAN-MANTEL-HAENSZEL STATISTICS, TYPICALLY FOR STRATIFIED TWO-WAY 
													TABLES

						EXACT						REQUESTS FISHER’S EXACT TEST FOR TABLES LARGER THAN 2X2. 

						MEASURES					REQUESTS MEASURES OF ASSOCIATION INCLUDING PEARSON AND SPEARMAN CORRELATION 
													COEFFICIENTS, GAMMA, KENDALL’S TAU-B, STUART’S TAU-C, SOMER’S D, LAMBDA, ODDS 
													RATIOS, RISK RATIOS, AND CONFIDENCE INTERVALS

						RELRISK						REQUESTS RELATIVE RISK MEASURES FOR 2X2 TABLES

						TREND						REQUESTS THE COCHRAN-ARMITAGE TEST FOR TREND;

DATA BUS;
INFILE "D:\Practice\SAS\Little SAS Book\Data\Bus.csv" DSD DLM=",";
INPUT BUSTYPE$ ONTIMEORLATE$ @@;
RUN;

PROC FREQ DATA = BUS;
TABLES BUSTYPE  * ONTIMEORLATE / CHISQ;
TITLE;
RUN;			*


G)	CREATING STATISTICAL GRAPHICS WITH PROC FREQ

	--->	THE FREQ PROCEDURE USES ODS GRAPHICS TO PRODUCE SEVERAL PLOTS THAT HELP YOU VISUALIZE YOUR DATA INCLUDING FREQUENCY PLOTS, ODDS RATIO
			PLOTS, AGRREMENT PLOTS, DEVIATION PLOTS AND TWO TYPES OF PLOTS WITH KAPPA STATISTICS AND CONFIDENCE LIMITS. HERE IS TH GENERAL FORM OF
			PROC FREQ WITH PLOT OPTIONS;

							PROC FREQ; 
							TABLES variable-combinations / options PLOTS = (plot-list); 
							RUN;

*	--->	PLOT REQUESTS - THE PLOTS AVAILABLE TO YOU DEPENDS ON THE TYPE OF TABLE YOU REQUEST. FOR EXAMPLE, THE "DEVIATIONPLOT" IS ONLY
			AVAILABLE FOR ONE-WAY TABLES WHEN USING "CHISQ" OPTION ON THE TABLES STATEMETS. HERE ARE THE PLOTS YOU CAN REQUEST ALONG WITH THE
			REQUIRED OPTION. IF ANY AND TYPE OF TABLE REQUEST:

					PLOT NAME					TABLE TYPE							REQUIRED OPTION ON TABLE STATEMENT

					AGREEPLOT					TWO-WAY								AGREE
					CUMFREQPLOT					ONE-WAY
					DEVIATIONPLOT				ONE-WAY								CHISQ
					FREQPLOT					ANY-REQUEST
					KAPPAPLOT					THREE-WAY							AGREE
					ODDSRATIOPLOT				HX2X2								MEASURES or RELRISK
					RELRISKPLOT					HX2X2								MEASURES or RELRISK
					RISKDIFPLOT					HX2X2								RISKDIFF
					WTKAPPAPLOT					HXRXR(R>2)							AGREE

	--->	TO PRODUCE A "CUMFREQPLOT" o "FREQPLOT", YOU MUST SPECIFY IT IN THE "PLOTS=" OPTION OF THE "TABLES" STATEMENT. OTHERWISE IF YOU DO
			NOT SPECIFY ANY PLOTS IN THE TABLE STATEMENT, THEN ALL PLOTS ASSOCIATED WITH THE TABLE YOU REQUEST WILL BE PRODUCE BY DEFAULT.

	--->	PLOT OPTIONS -- MANY OPTIONS ARE VAILABLE THAT CONTROL THE LOOK OF PLOTS GENERATED. FOR A COMPLETE LIST IF OPTIONS, SEE THE SAS HELP
			AND DOCUMENTATION. FOR EXAMPLE, THE "FREQPLOT" HAS OPTIONS FOR CONTROLLING THE LAYOUT OF THE PLOTS FOR TWO-WAY TABLES. BY DEFAULT, 
			THE BARS ARE GROUPED CALY. TO GROUP THE BARS HORIZONTALLY, USE;

							TABLES variable1 * variable2 / PLOTS = FREQPLOT(TWOWAY = GROUPHORIZONTAL);

*	--->	TO STACK BARS, USE THE "TWOWAY=STACKED" OPTION.;

DATA BUS;
INFILE "D:\Practice\SAS\Little SAS Book\Data\Bus.csv" DSD DLM=",";
INPUT BUSTYPE$ ONTIMEORLATE$ @@;
RUN;
proc print data = BUS;
run;
PROC FORMAT ;
VALUE $TYPE	'R'= 'REGULAR'
			'E'='EXPRESS';
VALUE $LATE 'O'= 'ON TIME'
			'L'= 'LATE';
RUN;
PROC FREQ DATA = BUS;
TABLE BUSTYPE * ONTIMEORLATE / PLOTS = FREQPLOT(TWOWAY=GROUPHORIZONTAL);
FORMAT BUSTYPE $TYPE. ONTIMEORLATE $LATE.;
RUN;			*


H)	EXAMINING CORRELATIONS WITH PROC CORR

	--->	THE CORR PROCEDURE, WHICH IS INCLUDED WITH BASE SAS SOFTWARE, COMPUTES CORRELATIONS. A CORRELATION COEFFICIENT MEASURES THE STRENGTH
			OF THE LINER RELATIONSHIP BETWEEN TWO VARIABLES. IF TWO VARIABLES ARE COMPLETELY UNRELATED, THEY WILL HAVE A CORRELATION OF 0. IF TWO
			VARIABLES HAVE A PERECT LINER RELATIONSHIP, THEY WILL HAVE A CORRELATION OF 1.0, IN REAL LIFE, CORRELATIONS FALL SOMEWHERE BETWEEN
			NUMBERS. THE BASIC STATEMENT FOR PROC CORR IS RATHER SIMPLE:
			
								PROC CORR:

	--->	THESE TWO WORDS TELL SAS TO COMPUTE CORRELATION BETWEEN ALL POSSIBLE PAIRS OF NUMERIC VARIABLES. YOU CAN ADD THE "VAR" AND "WITH"
			STATEMENTS TO SPECIFY VARIABLES:

								VAR variable-list: 
								WITH variable-list;


DATA TEST;
INFILE "D:\Practice\SAS\Little SAS Book\Data\Test Score.csv" DSD DLM=',';
INPUT SCORE TELEVISION EXCERCISE @@;
RUN;
PROC CORR DATA = TEST;
VAR TELEVISION EXCERCISE;
WITH SCORE;
TITLE1 "CORRELATION FOR TEST SCORE";
TITLE2 "WITH HOURS OF TELEVISION AND EXERCISE";
RUN;			*


J)	CREATING STATISTICAL GRAPHICS WITH PROC CORR

	--->	THE CORR PROCEDURE EVALUATES THE STRENGTH OF THE LINER RELATIONSHIP BETWEEN PARIS OF VARIABLES. THE TABULAR OUTPUT GIVES THE
			CORRELCATION COEFFICIENTS AND OTHER SIMPLE STATISTICS, AND USING ODS GRAPHICS YOU CAN ALSO VISUALIZE THE RELATIONSHIP. PLOTS ARE NOT
			GENERATED BY DEFAULT, SO YOU NEED TO SPECIFY THE DESIRED PLOTS USING THE "PLOTS=" OPTION. HERE IS GENERAL FORM OF "PROC CORR" WITH
			THE "PLOTS" OPTION.;

						PROC CORR PLOT = (plot-list);
						VAR variable-list;
						WITH variable-list;
						RUN;

*	--->	PLOT REQUESTS -- THE "CORR" PROCEDURE CAN PRODUCE TWO TYPES OF PLOTS:
					SCATTER - CREATES SCATTER PLOTS FOR PAIRS OF VARIABLES. PREFICTION OR CONFIDENCE ELLIPSES ARE OVERLAID ON THE PLOT.
					MATRIX 	- CREATES A MATRIX OF SCATTER PLOTS FOR ALL VARIABLES.

	--->	PLOT OPTIONS - BY DEFAULT, THE SCATTER PLOTS INCULDE PREDICTION ELLIPSES FOR NEW OBSERVATIONS. IF YOU WANT CONFIDENCE ELLIPSES FOR
			MEANS, THEN SPECIFY THE "ELLIPSE=CONFIDENCE" OPTION ON THE SCATTER PLOT:

						PROC CORR PLOTS = SCATTER(ELLIPSE = CONFIDENCE)

	--->	IF YOU DO NOT WANT ANY ELLIPSES ON YOUR SCATTER PLOTS, THEN USE THE "ELLIPSE=NONE" OPTION.

	--->	IF YOU DO NOT HAVE A "WITH" STATEMENT, THEN MATRIX PLOTS WILL SHOW A SYMMETRICAL PLOT WITH ALL VARIABLE COMBINATIONS APPEARING TWICE.
			BY DEFAULT THE DIAGONAL CELLS IN THE MATRIX WILL BE EMPTY. IF YOU USE THE "HISTOGRAM" OPTION FOR THE MATRIX PLOT, THEN A HISTOGRAM 
			WILL BE PRODUCED FOR EACH VARIABLE AND DISPLAYED ALONG THE DIAGONAL.;

						PROC CORR PLOTS = MATRIX(HISTOGRAM);


PROC CORR DATA = TEST PLOT = (SCATTER MATRIX);
VAR TELEVISION EXCERCISE;
WITH SCORE;
TITLE1 "CORRELATION FOR TEST SCORE";
TITLE2 "WITH HOURS OF TELEVISION AND EXERCISE";
RUN;			*


K)	USING PROC REG FOR SIMPLE REGRESSION ANALYSIS

	--->	THE "REG" PROCEDURE FITS LINER REGRESSION MODELS BY LEAST-SQUARES AND IS ONE OF MANY SAS PROCEDURES WHICH PERFORM REGRESSION 
			ANANLYSIS. "PROC REG" IS PAR OF SAS/STAT, WHICH IS LICENSED SEPARATELY FROM BASE SAS SOFTWARE. WE WILL SHOW AN EXAMPLE FOR A
			SIMPLE REGRESSION ANALYSIS USING CONTINUOUS NUMERIC VARIABLES WITH ONLY ONE REGRESSOR VARIBALE. HOWEVER, "PROC REG" IS CAPABLE
			OF ANALYZING MEODELS WITH MANY REGRESSOR VARIABLES USING A VARIETY OF MODEL-SELECTION METHODS INCLUDING STEPWISE REGRESSION, FORWARD
			SELECTION, AND BACKWARD ELIMINATION. OTHER PROCEDURES IN SAS/STAT WILL PERFORM NON-LINER AND LOGISTIC REGRESSION. IN SAS/ETS YOU
			WILL FIND PROCEDURES FOR TIME SERIES ANALYSIS. IF YOU ARE UNSURE ABOUT WHAT TYPE OF ANALYSIS YOU NEED, OR ARE UNFAMILIAR WITH 
			BASIC STATISTICAL PRINCIPLES, WE RECOMMEND THAT YOU SEEK ADVICE FROM TRAINED STATISTICIAN, OR CONSULT A GOOD STATISTICAL TEXTBOOK.

	--->	THE "REG" PROCEDURE HAS ONLY TWO REQUIRED STATEMENT. IT MUST START WITH THE "PROC REG" STATEMENT AND HAVE A "MODEL" STATEMENT 
			SPECIFYING THE ANALYSIS MODEL. THE FOLLOWING SHOWS THE GENERAL FORM OF THE "REG" PROCEDURE:
							PROC REG:
							MODEL dependent = independent:

	--->	IN THE "MODEL" STATEMENT, THE DEPENDENT VARIABLE IS LISTED ON THE LEFT SIDE OF THE EQUAL SIGN AND THE INDEPENDENT, OR REGRESSOR,
			VARIABLE IS LISTED ON THE RIGHT.;


DATA BALLGAME;
INFILE "D:\Practice\SAS\Little SAS Book\Data\T-Ball Game.csv" DSD DLM=',';
INPUT HEIGHT DISTANCE @@;
RUN;
PROC REG DATA = BALLGAME;
MODEL DISTANCE = HEIGHT;
TITLE "RESULTS OF REGRESSION ANALYSIS";
RUN;			*

L)	CREATING STATISTICAL GRAPHICS WITH PROC REG

	--->	THERE ARE MANY PLOTS THAT ARE USEFUL FOR VISUALIZING THE RESULTS OF REGRESSION ANALYSIS AND FOR ASSESSING HOW WELL THE MODEL FITS 
			THE DATA. PROC REG USES ODS GRAPHICS TO PRODUCE MANY SUCH PLOTS INCLUDING A DIAGNOSTIC PANEL THAT CONTAINS UP TO NINE PLOTS IN ONE 
			FIGURE. SOME PLOTS ARE PRODUCED AUTOMATICALLY WHILE OTHERS NEED TO BE SPECIFIED. HERE IS THE GENERAL FORM OF PROC REG WITH THE PLOTS 
			OPTION;


							PROC REG PLOTS(options) = (plot-request-list); 
							MODEL dependent = independent; 
							RUN;

*	--->	PLOT REQUESTS  HERE ARE SOME PLOTS YOU CAN REQUEST FOR SIMPLE LINEAR REGRESSION:

					FITPLOT							SCATTER PLOT WITH REGRESSION LINE AND CONFIDENCE AND 
													PREDICTION BANDS

					RESIDUALS						RESIDUALS PLOTTED AGAINST INDEPENDENT VARIABLE 

					DIAGNOSTICS						DIAGNOSTICS PANEL INCLUDING ALL OF THE FOLLOWING PLOTS 

					COOKSD							COOK’S D STATISTIC BY OBSERVATION NUMBER 

					OBSERVEDBYPREDICTED 			DEPENDENT VARIABLE BY PREDICTED VALUES

					QQPLOT 							NORMAL QUANTILE PLOT OF RESIDUALS

					RESIDUALBYPREDICTED 			RESIDUALS BY PREDICTED VALUES

					RESIDUALHISTOGRAM 				HISTOGRAM OF RESIDUALS

					RFPLOT 							RESIDUAL FIT PLOT

					RSTUDENTBYLEVERAGE 				STUDENTIZED RESIDUALS BY LEVERAGE

					RSTUDENTBYPREDICTED 			STUDENTIZED RESIDUALS BY PREDICTED VALUES


	--->	EXCLUDING AUTOMATIC PLOTS -- BY DEFAULT  THE RESIDUALS AND DIAGNOSTICS PLOTS ARE GENERATED AUTOMATICALLY. ADDITIONAL PLOTS MAY ALSO 
			BE PRODUCED BY DEFAULT DEPENDING ON THE TYPE OF MODEL. FOR EXAMPLE, A FITPLOT IS AUTOMATICALLY GENERATED WHEN THERE IS ONE REGRESSOR 
			VARIABLE. IF YOU CHOOSE SPECIFIC PLOTS IN THE PLOT-REQUEST-LIST, THE DEFAULT PLOTS WILL STILL BE CREATED UNLESS YOU USE THE ONLY 
			GLOBAL OPTION; 

								PROC REG PLOTS(ONLY) = (PLOT-REQUEST-LIST); 

PROC REG DATA = BALLGAME PLOTS(ONLY) = (DIAGNOSTICS FITPLOT); 
MODEL Distance = Height; 
TITLE 'Results of Regression Analysis'; 
RUN;		*


M)	USING PROC ANOVA FOR ONE-WAY ANALYSIS OF VARIANCE

	--->	THE ANOVA PROCEDURE IS ONE OF MANY IN SAS THAT PERFORM ANALYSIS OF VARIANCE. PROC ANOVA IS PART OF SAS/STAT, WHICH IS LICENSED 
			SEPARATELY FROM BASE SAS SOFTWARE. PROC ANOVA IS SPECIFICALLY DESIGNED FOR BALANCED DATA—DATA WHERE THERE ARE EQUAL NUMBERS OF 
			OBSERVATIONS IN EACH COMBINATION OF THE CLASSIFICATION FACTORS. AN EXCEPTION IS FOR ONE-WAY ANALYSIS OF VARIANCE WHERE THE DATA 
			DO NOT NEED TO BE BALANCED. IF YOU ARE NOT DOING ONE-WAY ANALYSIS OF VARIANCE AND YOUR DATA ARE NOT BALANCED, THEN YOU SHOULD USE 
			THE GLM PROCEDURE, WHOSE STATEMENTS ARE ALMOST IDENTICAL TO THOSE OF PROC ANOVA. ALTHOUGH WE ARE DISCUSSING ONLY SIMPLE ONE-WAY 
			ANALYSIS OF VARIANCE IN THIS SECTION, PROC ANOVA CAN HANDLE MULTIPLE CLASSIFICATION VARIABLES AND MODELS THAT INCLUDE NESTED AND 
			CROSSED EFFECTS AS WELL AS REPEATED MEASURES. IF YOU ARE UNSURE OF THE APPROPRIATE ANALYSIS FOR YOUR DATA, OR ARE UNFAMILIAR WITH 
			BASIC STATISTICAL PRINCIPLES, WE RECOMMEND THAT YOU SEEK ADVICE FROM A TRAINED STATISTICIAN OR CONSULT A GOOD STATISTICAL TEXTBOOK. 

	--->	THE ANOVA PROCEDURE HAS TWO REQUIRED STATEMENTS: THE CLASS AND MODEL STATEMENTS. THE FOLLOWING IS THE GENERAL FORM OF THE ANOVA 
			PROCEDURE;

							PROC ANOVA; 
							CLASS variable-list; 
							MODEL dependent = effects; 

DATA BASKETBALL;
INFILE "D:\Practice\SAS\Little SAS Book\Data\Basketball.csv" DSD DLM=",";
INPUT REGION$ HEIGHT @@;
RUN;
PROC ANOVA DATA = BASKETBALL;
CLASS REGION;
MODEL HEIGHT = REGION;
MEANS REGION / SCHEFFE;
TITLE "GIRLS HEIGHT FROM FOUR REGION";
RUN;		*


N)	READING THE OUTPUT OF PROC ANOVA

	--->	THE TABULAR OUTPUT FROM PROC ANOVA HAS AT LEAST TWO PARTS. FIRST ANOVA PRODUCES A TABLE GIVING INFORMATION ABOUT THE CLASSIFICATION 
			VARIABLES: NUMBER OF LEVELS, VALUES, AND NUMBER OF OBSERVATIONS. NEXT IT PRODUCES AN ANALYSIS OF VARIANCE TABLE. IF YOU USE OPTIONAL 
			STATEMENTS LIKE MEANS, THEN THEIR OUTPUT WILL FOLLOW. THE EXAMPLE FROM THE PREVIOUS SECTION USED THE FOLLOWING PROC ANOVA STATEMENTS; 

						PROC ANOVA DATA = HEIGHTS; 
						CLASS REGION; 
						MODEL HEIGHT = REGION; 
						MEANS REGION / SCHEFFE; 
						TITLE "GIRLS' HEIGHTS FROM FOUR REGIONS"; 
						RUN;
