*
A) CONCEPTS OF ODS GRAPHICS

	--->	USING ODS GRAPHICS IN STATISTICAL PROCEDURES -- OVER 80 STATISTICAL PROCEDURES HAVE THE ABILITY TO PRODUCE GRAPHS USING "ODS" GRAPHICS.
			INCLUDED ARE PROCEDURES FROM BASE SAS, SAS/STAT, SAS/ETS, AND SAS/QC. WHEN YOU RUN THESE PROCEDURES. ODS GRAPHICS WILL PRODUCE GRAPHS
			THAT ARE SPECIALLY DESIGNED OR THAT TYPE OF ANALYSIS.

	--->	USING ODS GRAPHICS FOR STAND-ALONE GRAPHS -- ODS GRAPHICS ALSO INCLUDES A FAMILY OF PROCEDURES DESIGNED TO CREATE STAN-ALONE GRAPHS
			THE "SGPLOT" AND "SGPANEL" PROCEDURES ARE TWO OF THESE. BECASUE THESE PEOCEDURES ALWAYS PRODUCE GRAPHS, YOU DO NOT NEED TO SPECIFY.
			THE ODS GRAPHICS ON STATEMENT TO SPECIFY GRAPHICS OPTION.

	--->	THE "SGPLOT" PROCEDURE CREATES SINGLE-CELLED GRAPHS WHILE "SGPANEL" CAN CREATE MULTI-CELLED GRAPHS BASED ON CLASSIFICATION VARIABLES.
			THE VARIOUS TYPES OF GRAPHS FALL INTO THREE GENERAL CATEGORIES.

	--->			CATOGERY 										TYPE OF GRAPH
					X Y PLOTS										BAND, BUBBLE, ELIPSE, HIGH-LOW, LOESS, NEEDLE PENALIZED B-SPLINE, REGRESSION
																	SCATTER, SERIES, STEP AND VACTOR

					CONTINUOUS DISTRIBUTIONS						BOX, DESTINY AND HISTOGRAM

					CATEGORICAL DISTRIBUTION						DOT, BAR AND LINE


	--->	ODS DESTINATIONS -- STARTING WITH SAS 9.3, YOUR GARPHS WILL BE RENDERED, BY DEFAULT, IN HTML FOR THE SAS WINDOWING ENVIRONMENT ON 
			MACROSOFT WONDOW OR UNIX. THE TRANDITIONAL "LISTING" DESTINATION REMAINS THE DEFAULT WHEN YOU RUN IN BATCH AND IN OTHER OPERATING 
			ENVIRONMENTS.

	--->	SAVING GRAPHS -- ALSO STARTING WITH SAS 9.3, GRAPHS ARE WRITTEN IN YOUR "WORK" LIBRARY AND WILL THEREFORE BE DELETED WHEN YOU EXIST
			SAS, THIS IS GOOD BEACSUE IT PREVENTS YOUR DISK FROM BECOMING CLUTTERED WITH OLD GRAPHS. 

	--->	STYLE FOR THE GRAPHS -- ODS STYLE TEMPLATES CONTROL THE OVERALL APPEARANCE OF YOUR OUTPUT. YOU CAN USE THE SAME STYLE TEMPLATES 
			FOR GRAPHS AS FOR TABULAR OUTPUT. HOWEVER, SOME STYLES ARE BETTER SUITED TO STATISTICAL GRAPHICS THAN OTHERS. THE FOLLOWING TABLE
			LISTS STYLES THAT ARE RECOMMENDED FOR STATISTICAL RESULTS.

	--->			DESIRED OUPUT				STYLE NAME 							DEFAULT FOR DESTINATION

					COLOUR						ANALYSIS
												HTMLBLUE							HTML
												LISTING								LISTING(GRAPH ONLY)
												PRINTER								PRINTER, PDF, PF
												RTF									RTF
												STATISTICAL

					GRAY SCALE					JOURNAL

					BLACK AND WHITE				JOURNAL2

	--->	YOU CAN SPECIFY A STYLE FOR YOUR GRAPHS USING THE "STYLE=" OPTION IN THE ODS STATEMENT FOR A DESTINATION. FOR EXAMPLE, TO PRODUCE
			GRAY-SCALE GRAPHICS IN THE "LISTING" DESTINATION YOU WOULD USE THIS STATEMENT:

									ODS LISTING STYLE = JOURNAL:

	--->	VIEWING ODS GRAPHICS --  WHEN YOU PRODUCE "ODS" GRAPHICS IN THE SAS WONDOWING ENVIRONMENT, THE RESULTS VIWER WINDOW GENERALLY OPENS
			DISPLAYING YOUR RESULTS. HOWEVER, WHEN YOU USE THE LISTING DESTINATION, GRAPHS ARE NOT AUTOMATICALLY DESPLAYED. YOU CAN VIEW ANY
			GRAPH BY DOUBLE-CLICKING IT'S GRAPH ICON IN THE RESULT WINDOW.


B)	CREATING BAR CHARTS

	--->	BAR CHARTS SHOW THE DISTRIBUTION OF A CATEGORICAL VARIBALES WHERE THE LENGTH OF EACH BAR IS PROPORTIONAL TO THE NUMBER OF OBSERVATION
			IN THAT CATEGORY. TO CREATE A CHART WITH VERTICAL BARS, USE A "VBAR" STATEMENT WITH GENERAL FORM:

									PROC SGPLOT:
										VBAR variable-name / options:

	--->	FOR HORIZONTAL BARS, REPLACE THE KEYWORD "VBAR" WITH "HBAR", POSSIBLE OPTIONS INCLUDE

					ALPHA = n								SPECIFIES THE LEVEL FOR THE CONFIDENCE LIMITS. THE VALUE OF N MUST BE 
															BETWEEN 0(100% CONFIDENCE) AND 1 ( 0% CONFIDENCE LIMITS).

					BARWIDTH = n							SETS THE WIDTH OF BARS. VALUES RANGE FROM 0.1 TO 1 WITH A DEFAULT OF 0.8.

					DATALABEL = variable-name				DISPLAYS A LABEL FOR EACH BAR. IF YOU SPECIFY A VARIABLE NAME, THEN VALUES OF 
															THAT VARIABLE WILL BE USED. OTHERWISE, SAS WILL CALCULATE APPROPRIATE VALUES.

					DISCRETEOFFSET = n						OFFSETS BARS FROM MIDPOINTS WHICH IS USEFUL FOR OVERLAYING BAR CHARTS. THE VALUE
															MUST BE BETWEEN 0.5 (LEFT) AND +0.5(RIGHT). THE DEFAULT OS 0(NO OFFSET).

					LIMITSTAT = statistics					SPECIFIES THE TYPE OF LIMIT LINES TO BE SHOWN. POSSIBLE VALUES ARE CLM, STDDEV
															STDERR. THIS OPTION CAN'T BE USED WITH "GROUP=" OPTION. YOU MUST SPECIFY A 
															"RESPONSE=" OPTION AND "STAT=MEAN".

					MISSING									INCLUDES A BAR FOR MISSING VALUE.

					GROUP = variable-name					SPECIFIES A VARIBALE USED TO GROUP THE DATA

					GROUPDIPLAY = Type						SPECIFIES HOW TO DISPLAY GROUPED BARS. EITHER "STACK" OR "CLUSTER"

					RESPONSE = Variable-name				SPECIFIES A NUMERIC VALUE TO BE SUMRIZED 

					STAT = statistics						SPECIFIES A STATISTICS, EITHER FREQ, MEAN or SUM. FREQ IS DEFAULT IF THERE IS NO
															RESPONSE VARIABLE. SUM IS THE DEFAULT WHEN SPECIFY A RESPONSE VARIABLE. 

					TRANSPARENCY = n						SPECIFIES THE DEGREE OF TRANSPARENCY FOR THE BARS. THE VALUE OF n MUST BE BETWEEN
															0 (THE DEFAULT) AND 1, WITH ONE BEING COMPLETELY TRANSPARANT AND 0 BEING COMPLETELY
															OPAQUE.;


DATA CHOCOLATE;
INFILE "D:\Practice\SAS\Little SAS Book\Data\Chocolate Manufacturer.csv" DSD DLM="," FIRSTOBS=2;
INPUT AgeGroup$ Flavor$;
RUN;
PROC FORMAT ;
VALUE $AgeGp "A" = "Adult" "C" = "Child";
RUN;
PROC SGPLOT DATA = CHOCOLATE;
VBAR Flavor / GROUP = AgeGroup GROUPDISPLAY = CLUSTER;
FORMAT AgeGroup $AgeGP.;
LABEL Flavor = "Flavor Of Chocolate";
TITLE "FAVORITE CHOCOLATE FLAVOR BY AGE";
RUN;			*


C)	CREATING HISTOGRAMS AND DESTINY CURVES

	--->	THE BAR CHARTS IN THE PRECEDING SECTION SHOW THE DISTRIBUTION OF CATEGORICAL DATA. TO SHOW THE DISTRIBUTION OF CONTINUOUS DATA, YOU CAN 
			USE HISTOGRAM OR BOX PLOT. IN HISTOGRAM, THE DATA ARE DEVIDED INTO DISCRETE INTERVALS CALLED BINS. EACH BIN IS REPRESENTED BY A
			RECTANGLE WHICH MAKES HISTOGRAM LOOK SIMILAR TO VAR CHARTS. HOWEVER, BAR CHARTS TYPICALLY HAVE A GAP BETWEEN THE BARS WHILE HISTORGRAM
			DO NOT.

	--->	HISTOGRAM - TO CREATE A HISTOGRAM, USE A HISTOGRAM STATEMENT WITH THE BASIC FORM;
								PROC SGPLOT; 
								HISTOGRAM variable-name / options;


						BINSTART = n					SPECIFIES THE MID POINT OF FIRST BIN.

						BINWIDTH = n					SPECIFIES THE BIN WIDTH . SAS DETERMINES THE NUMBER OF BINS
														THIS OPTION IS IGNORED IF YOU SPECIFY THE NBINS=OPTIONS

						NBINS = n						SPECIFIES THE NUMBER OF BINS, SAS DETERMINES THE BIN WIDTH.

						SCALE = scaling-type			SPECIFIES THE SCALE FOR THE VERTICL AXIS, EITHER "PERCENT"
														(THE DEFAULT), COUNT, OR PROPORTION.

						SHOWBINS						PLACES TICKS MARKS AT THE MIDPOINTS OF THE BINS. BY DEFAULT,
														TICKS MARKS ARE PLACED AT REGUALR INTERVALS BASED ON MINIMUM
														AND MAXIMUM VALUE .

						TRANSPARENCY = n				SPECIFIES THE DEGREE OF TRANSPARENCY FOR THE HISTOGRAM. THE VALUE OF n MUST BE BETWEEN
														0 (THE DEFAULT) AND 1, WITH ONE BEING COMPLETELY TRANSPARANT AND 0 BEING COMPLETELY
														OPAQUE.;


*	--->	DESTINY CITVES - YOU CAN ALSO PLOT DESTINY CURVES FOR YOUR DATA. THE BASIC OF A DESTINY STATEMENT IS;

								PROC SGPLOT; 
								DENSITY variable-name / options;

			
					TYPE = distribution-type					SPECIFIES THE TYPE OF DISTRIBUTION CURVE, EITHER NORMAL(THE DEFAULT) OR KERNEL.

					TRANSPARENCY = n							SPECIFIES THE DEGREE OF TRANSPARENCY FOR THE HISTOGRAM. THE VALUE OF n MUST BE 
																BETWEEN 0 (THE DEFAULT) AND 1, WITH ONE BEING COMPLETELY TRANSPARANT AND 0 BEING 
																COMPLETELY OPAQUE .;


DATA CONTEST;
INFILE "D:\Practice\SAS\Little SAS Book\Data\Fourth Grade Class Competition.csv" DSD DLM=",";
INPUT StudentNames$	NumberBooks;
RUN;
PROC SGPLOT DATA = CONTEST;
HISTOGRAM NumberBooks / BINWIDTH = 2 SHOWBINS SCALE  = COUNT;
DENSITY NumberBooks;
DENSITY NumberBooks / TYPE = KERNEL;
TITLE "READING CONTEST";
RUN;			*


D)	CREATING BOX PLOT

	--->	LIKE HISTOGRAM, BOX PLOTS SHOW THE DISTRIBUTION OF CONTINUOUS DATA. THIS TYPE OF GRAPH IS ALSO CALLED BOX-AND-WHISKER PLOT BECAUSE
			OF THE WAY IT LOOKS. EVERY PART OF A BOX TELLS YOU SOMETHING ABOUT THE DISTRIBUTION OF YOUR DATA.

	--->	TO CREATE A VERTICAL BOX PLOT, USE A VBOX STATEMENT LIKE THIS;
									PROC SGPLOT; 
									VBOX variable-name / options;

*	--->				CATOGERY variable-name					SPECIFIES A CATEGORICAL VARIBALE. ONE BOX PLOT WILL BE CREATED FOR EACH
																VALUE OF THIS VARIABLE.

						EXTREME									SPECIFIES THAT THE WHISKERS SHOULD EXTEND TO THE TRUE MINIMUM AND MAXIMUM
																VALUES SO OUTLIERS WILL NOT BE IDENTIFIED.

						GROUP = variable-name					SPECIFIES A SECOND CATEGORICAL VARIABLE. ONE BOX PLOT WILL CREATED FOR EACH VALUE
																OF THIS VARIBALE WITHIN CATEGORICAL VARIABLE.

						MISSING									INCLUDES A BOX FOR MISSING VALUES FOR THE GROUP OR CATEGORY VARIABLE.

						TRANSPARENCY = n						SPECIFIES THE DEGREE OF TRANSPARENCY FOR BOX PLOT. THE VALUE OF n MUST BE 
																BETWEEN 0 (THE DEFAULT) AND 1, WITH ONE BEING COMPLETELY TRANSPARANT AND 0 BEING 
																COMPLETELY OPAQUE .


	--->	THE "VBOX" AND "HBOX" STATEMENTS CAN'T BE USED WITH STATEMENTS THAT CREATE OTHER TYPES OF PLOTS.;

DATA BIKERACE;
INFILE "D:\Practice\SAS\Little SAS Book\Data\Annual Bicycle Criterium.csv" DSD DLM="," FIRSTOBS=2;
INPUT DIVISION$ LAPS;
RUN;
PROC SGPLOT DATA = BIKERACE;
VBOX LAPS / CATEGORY = DIVISION;
TITLE 'Bicycle Criterium Results by Division';
RUN;			*


E)	CREATING SCATTER PLOTS

	--->	SCATTER PLOTS ARE AN EFFECTIVE WAY TO SHOW THE RELATIONSHIP BETWEEN TWO CONTINUOUS VARIBALE. FOR EXPERIMENTAL DATA, THE INDEPENDENT
			VARIABLE IS TRADITIONALLY ASSIGNED TO THE HORIZONTAL AXIS WHILE THE DEPENDENT VARIBALE IS ASSIGNED TO THE VARTICAL AXIS. TO CREATE
			SCATTER PLOTS, USE THE SCATTER STATEMENT LIKE THIS.;

								PROC SGPLOT; 
								SCATTER X=horizontal-variable Y=vertical-variable / options;

*	--->	DATALABEL = variable-name					DISPLAY A LABEL FOR EACH DATA POINT. IF YOU SPECIFY A VARIABLE NAME, THE VALUE OF
														THAT VARIABLE WILL BE USED AS LABELS. IF YOU DO NOT SPECIFY A VARIABLE NAME, THEN 
														THE VALUE OF "Y" VARIABLE WILL BE USED.

			GROUP = varibale-name						SPECIFIES A VARIABLE TO BE USED FOR GROUPING DATA.

			NOMISSINGGROUP								SPECIFIES THAT OBSERVATION WITH MISSING VALUES FOR THE GROUP VARIABLE SHOULD BE INCLUDED.
			
			TRANSPARENCY = n							SPECIFIES THE DEGREE OF TRANSPARENCY FOR BOX PLOT. THE VALUE OF n MUST BE 
														BETWEEN 0 (THE DEFAULT) AND 1, WITH ONE BEING COMPLETELY TRANSPARANT AND 0 BEING 
														COMPLETELY OPAQUE .;


DATA wings; 
INFILE "D:\Practice\SAS\Little SAS Book\Data\Birds.csv" DSD DLM=","; 
INPUT Name : $12. Type : $2. Length Wingspan; 
RUN; 
* Plot Wingspan by Length; 
PROC FORMAT; 
VALUE $birdtype 
'S' = 'Songbirds' 
'R' = 'Raptors'; 
RUN; 
PROC SGPLOT DATA = wings; 
SCATTER X = Wingspan Y = Length / GROUP = Type; 
FORMAT Type $birdtype.; 
TITLE 'Comparison of Wingspan vs. Length'; 
RUN; 			*


F)	CREATING SERIES PLOTS

	--->	A SERIES PLOT IS SIMILAR TO A SCATTER PLOT EXCEPT THAT INSTEAD OF MAKING EACH DATA POINT, SAS CONNECTS THE DATA POINTS WITH A LINE.
			SERIES PLOTS MAKE SENSE WHENEVER DATA MUST BE DISPLAYED IN A PARTICULAR ORDER. DATES AND TIMES OF ANY KIND ARE GOOD CONDIDATES FOR
			SERIES PLOTS. TO CREATE A SERIES PLOT, USE A "SERIES STATEMENT" WITH THIS BASIC FORM;

								PROC SGPLOT; 
   								SERIES X=horizontal-variable Y=vertical-variable / options;
*
					
					CURVELABEL = 'text-string' 									ADDS A LABEL FOR THE CURV. IF YOU DO NOT SPECIFY A TEXT STRING
																				THEN SAS USES THE LABEL FROM THE "Y" VARIABLE.

					DATALABEL = variable-name 									displays a label for each data point. If you specify a 
																				variable name, the values of that variable will be used 
																				as labels. If you do not specify a variable name, then 
																				the values of the Y variable will be used. 

					GROUP = variable-name 										specifies a variable to be used for grouping the data. A 
																				separate line is created for each unique value of the 
																				grouping variable.

					MARKERS 													adds a marker for each data point. 

					NOMISSINGGROUP 												specifies that observations with missing values for the 
																				group variable should not be included. 

					TRANSPARENCY = n 											specifies the degree of transparency for plot line. The 
																				value of n must be between 0 (the default) and 1, with 
																				1 being completely transparent and 0 being 
																				completely opaque;

DATA ELECTRICITY;
INFILE "D:\Practice\SAS\Little SAS Book\Data\Electricity For One Day.csv" DSD DLM=",";
INPUT Time kWh @@;
RUN; 
* Plot temperatures by time; 
PROC SGPLOT DATA = electricity; 
SERIES X = Time Y = kWh / MARKERS; 
TITLE 'Hourly Use of Electricity'; 
RUN; 		*


G)		CREATING FITTED CURVES

		--->	SCATTERS PLOTS SHOW THE RELATION BETWEEN TWO VARIABLES. ONE WAY TO EXPLORE THAT RELATIONSHIP FURTHER IS TO PLOT FITTED CURVE.
				THE SGPLOT PROCEDURE PRODUCES SEVERAL KINDS OF FITTEN CURVES INCLUDIN REGRESSION LINES, LOESS CURVES AND PENALIZED B-SPLINE
				CURVES. TO CREATE ANY OF THESE TYPES OF FITTED CURVES, USE A STATEMENT WITH THIS GENERAL FORM;

									PROC SGPLOT; 
									statement-name X=horizontal-variable Y=vertical-variable / options; 

*		--->	WHERE THE Where the statement-name CAN BE

				REG				REGRESSION LINE OR CURVE
				LOESS			LOESS CURVE
				PBSPLINE		PENELIZED B-SPLIN


		--->	OPTIONS FOR FITTED CURVE INCLUDES 

							ALPHA = n						specifies the level for the confidence limits. The 
															value of n must be between 0 (100% confidence) and 
															1 (0% confidence). The default is  0.05 (95% 
															confidence limits). 

							CLI								adds prediction limits for individual predicted 
															values  (for REG and PBSPLINE only). 

							CLM								adds confidence limits for mean predicted values. 

							CURVELABEL = 'text-string' 		adds a label for the curve. If you do not specify a 
															text string, then SAS uses the label from the Y 
															variable.

							GROUP = variable-name			specifies a variable to be used for grouping the data. 
															A separate line is created for each unique value of 
															the grouping variable. 

							NOLEGCLI						removes legend entry for CLI band.

							NOLEGCLM						removes legend entry for CLM band. 

							NOLEGFIT						removes legend entry for fit curve. 

							NOMARKERS 						removes markers for data points. 

							CLMTRANSPARENCY = n				specifies the degree of transparency for the 
															confidence limits. The value of n must be between 0 
															(the default) and 1, with 1 being completely 
															transparent and 0 being completely opaque. ;




DATA Olympic1500; 
   INFILE "D:\Practice\SAS\Little SAS Book\Data\Winning Race Times.csv" DSD DLM=','; 
   INPUT Year Men @@; 
RUN; 
PROC SGPLOT DATA = Olympic1500; 
   LOESS X = Year Y = Men / NOMARKERS CLM NOLEGCLM; 
   REG X = Year Y = Men; 
   LABEL Men = 'Time in Seconds'; 
   TITLE "Olympic Times for Men's 1500 Meter Run"; 
RUN; 
